### ISSUE TITLE
Telemetry IP missing from the block-telemetry.ps1

### ISSUE THREAD

**Issue by Yersh** [W4RH4WK/Debloat-Windows-10#100]
I got installed windows 10 1607 LTSB 14393.729 and watched it with wireshark after applying the anti-telemetry script.
Windows connected to 184.86.53.99 which corresponds to the address: a184-86-53-99.deploy.static.akamaitechnologies.com

Seems it some kind of telemetry. And adding 0.0.0.0 a184-86-53-99.deploy.static.akamaitechnologies.com
to your host file doesn't stop windows from connecting to this address.

**Comment by W4RH4WK** [comment]
If a services connects directly via the IP address, no DNS look happens, therefore the hosts file is not considered. We have to resort to the Windows Firewall for blocking IPs directly.

Thanks for this information, I'll add the 2 entries in a bit.
