### ISSUE TITLE
No documentation on changes made

### ISSUE THREAD

**Issue by Andrew-Dunn** [W4RH4WK/Debloat-Windows-10#102]
At the moment there is no documentation on the changes these scripts will make to your computer. A simple list of changes would make me much more likely to use this.

**Comment by W4RH4WK** [comment]
There will not be a dedicated list, as it may get out of sync easily.

The recommended way of using these scripts is to look at them and modify them before execution. The name of a script, plus its description header and containing echo statements should give enough hints on what is going on.
