### ISSUE TITLE
Scripts don't work correctly unless they are elevated.

### ISSUE THREAD

**Issue by Tyestor** [W4RH4WK/Debloat-Windows-10#103]
I had a ton of issues getting scripts working correctly until I added a code snippet to each script that self-elevated Powershell. My user account is admin, but it is unelevated. I use UAC. Unlike batch scripts, you cannot right-click run as admin. This is the code I used. I should also probably mention that I edited registry permissions (with regini and manually) and Windows folder permissions (with icacls) and that lowered the error count a lot. But this self-elevating code snippet removed a number of errors, an example of two being: in the One Drive script, there was a firewall error and when adding IPs to the firewall and access denied error when trying to edit the hosts file.

```
param([switch]$Elevated)
function Check-Admin {
$currentUser = New-Object Security.Principal.WindowsPrincipal $([Security.Principal.WindowsIdentity]::GetCurrent())
$currentUser.IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
}
if ((Check-Admin) -eq $false)  {
if ($elevated)
{
# could not elevate, quit
}
 
else {
 
Start-Process powershell.exe -Verb RunAs -ArgumentList ('-noprofile -noexit -file "{0}" -elevated' -f ($myinvocation.MyCommand.Definition))
}
exit
}
```

**Comment by W4RH4WK** [comment]
I just added some clarification to the README.

**Comment by Tyestor** [comment]
Thanks.
