### ISSUE TITLE
Start menu broken after executing script

### ISSUE THREAD

**Issue by StijnT** [W4RH4WK/Debloat-Windows-10#105]
When I execute this script, the start menu of all the new users is broken. Meaning it will still show the uninstalled apps but they don't respond to anything.

I tried with replacing the default user's vedatamodel.edb with that of my account (which still has a working start menu). The new users then get the same start menu but it is still broken since it ignores any customization to the start menu xml

I am at a loss as to why this happens and how I can prevent it.

**Comment by W4RH4WK** [comment]
Did you run the `experimental_unfuckery.ps1` script?

**Comment by StijnT** [comment]
No only the remove-default-apps.ps1

I tried it dozens of times, every time on a fresh install of Windows 10 Enterprise.
Both the 1511 and 1607 iterations.

**Comment by dajuric** [comment]
It seems that disabling ShellExperienceHost causes this problem (when the app folder is renamed).

**Comment by W4RH4WK** [comment]
@dajuric yes, but this does not happen when running `remove-default-apps.ps1`. For this i supplied a dedicated script `utils/disable-ShellExperienceHost.bat`.

**Comment by dajuric** [comment]
Yes.
For me executing remove-default-apps went just fine.

**Comment by jlovell999** [comment]
Issue: After running "utils/disable-searchUI.bat" and rebooting, the start menu stops working, like completely.   

(not sure if I should have created a new issue, but this was close enough to the same thing that I appended here.)     

Symptoms are start button brings up the menu, but left click does nothing and  right click does not bring up the appropriate context menu.   Basically, on ANY object/item on the start menu (tiles, app list, settings button, power button etc), the mouse/pointer does not work.   You might as well be left or right clicking on a jpeg.   The Start Menu button on the taskbar itself works normally.   On any item/object outside of the start menu, the mouse buttons left and right work normally.  Multiple reboots did not fix the issue.  Issue tested and occurred with two different userid's on the PC.   As soon as the "Cortana" directory in "SystemApps" was re-enabled (within seconds), the start menu mouse functionality was back to normal.    This was without a reboot, however, I rebooted just to be safe.   

The "implication" here is that Microsoft has somehow tied the "searchUI" functions to the start menu heavily now (not "keyboard logging" but "mouse click logging").   Clever if not sleazy.   I have not tried this on my other Win10 machine but wanted to report back here as a helpful notice. 

Specifications: 
windows 10 creators update 1703 
winver: Version 1703 (OS Build 15063.540) 
scripts stamped 8/28/2017 
scripts run on 9/5/2017
scripts that were run: 
 utils/disable-scheduled-tasks.ps1 
 utils/disable-searchUI.bat 
 utils/enable-god-mode.ps1
 scripts/remove-default-apps.ps1
 scripts/disable-services.ps1
 scripts/optimize-user-interface.ps1
 scripts/optimize-windows-update.ps1

**Comment by W4RH4WK** [comment]
I know about this issue, and that's mainly the reason why *disable-searchUI* has been moved to the utils folder. It is intended to be used with a start menu replacement (like *classic shell* or *start is back*). There is also a note in the README about the whole start menu issue and that I do not recommend using the official one.

**Comment by gxgl** [comment]
Hello, 

I think a simple reg key to hide it will be good.

⁣It is an idea.

Pe 6 sept. 2017, 19:48, la 19:48, Alex Hirsch <notifications@github.com> a scris:

**Comment by W4RH4WK** [comment]
@gxgl Hide what? I cannot follow you.

**Comment by gxgl** [comment]
The search... but ignore that. 

Wishing you the best

⁣Trimis de la TypeApp ​

Pe 6 sept. 2017, 21:35, la 21:35, Alex Hirsch <notifications@github.com> a scris:

**Comment by koshibb** [comment]
Hi there - coming to this a few years later, wondering how i would go about fixing or re-enabling ShellExperienceHost. Currently when in start menu, i am unable to click on most apps.

**Comment by henriquedesousa** [comment]
My solution was to install Classic Menu. I still use that installation after all these years.
