### ISSUE TITLE
Holo crap

### ISSUE THREAD

**Issue by ThiloL** [W4RH4WK/Debloat-Windows-10#117]
How  to remove Holographics crap from Creators Update?

**Comment by W4RH4WK** [comment]
Apparently, even with the creators update installed this is not shown on systems not meeting some of its requirements. So try removing your two GTX 1080 Ti s from your rig and use the on board graphics -- should solve the problem.  Just kidding.

I have the Creators Update only installed on my work machine and even though it has a GTX 970 it does not show up for me. Maybe since the CPU is too old. Anyway the first thing I found was a [registry key], have you tried that already?

[registry key]: <http://winaero.com/blog/add-remove-mixed-reality-settings-windows-10/>

**Comment by W4RH4WK** [comment]
I have also seen that uninstall button?

![image](https://cloud.githubusercontent.com/assets/328798/26403742/9deee5ca-408f-11e7-9292-f8157ae7f4fe.png)

**Comment by ThiloL** [comment]
I want to **offline** service the image like https://technet.microsoft.com/en-us/library/dd744294(v=ws.10).aspx
UI optione doesn't help me in this case. 

dism /disable-feature 
dism /remove-package
or remove-appxprovisionedpackage would be fine :-)

**Comment by W4RH4WK** [comment]
You could try using dism like it is used in `experimental_unfuckery.ps1`. Yet there is a high probability it will break something in the long run.

**Comment by W4RH4WK** [comment]
Also have you tried this: <http://winaero.com/blog/uninstall-mixed-reality-windows-10/>?

**Comment by ThiloL** [comment]
**Dism /online /Get-Capabilities** doesn't list any holo stuff on my machine

**Comment by W4RH4WK** [comment]
Tomorrow I'll try to capture what happens when you hit that uninstall button. Maybe this somehow helps.

**Comment by ThiloL** [comment]
Yes. This stuff confuses our users. I hate Microsoft for doing this - placing useles stuff in user's start menu.

**Comment by W4RH4WK** [comment]
If this is just about the start menu, have a look at #115.

**Comment by ThiloL** [comment]
The all apps area is the problem. So, un-pinning is no solution.

**Comment by W4RH4WK** [comment]
Sorry for the late answer, I haven't found time over the weekend to get to this issue. Maybe the following information does help. Upon pressing the uninstall button the following command is executed:

    C:\Windows\System32\SystemSettingsAdminFlows.exe HolographicUninstall

If you intend to automate the uninstall process you may have to resort to an AutoIt script or similar. I haven't found a way to fully automate that process.

**Comment by ThiloL** [comment]
Start menu entry isn't removed with the uninstall. :-(

**Comment by W4RH4WK** [comment]
Apparently MS cannot even get the uninstaller right...

**Comment by W4RH4WK** [comment]
Just to be sure, you did reboot the machine. If it's still present can you provide me a screenshot as I cannot find it in my VM where I used the uninstaller.

![image](https://cloud.githubusercontent.com/assets/328798/26581018/ea669948-453a-11e7-99e1-8ff4232ad9ca.png)


![image](https://cloud.githubusercontent.com/assets/328798/26581007/df2a8256-453a-11e7-9333-416572c678dd.png)

**Comment by ThiloL** [comment]
Here https://www.administrator.de/frage/build-15063-1703-alte-app-thema-unternehmen-pro-edition-333525.html I found a cool way to remove this crap. I currently trying it.

**Comment by ThiloL** [comment]
**Mixed-Reality-Portal** only is in the start menu if you make a in-place upgrade from 1607 to 1703.

**Comment by W4RH4WK** [comment]
Okay, that would explain why I do not have it on my VM, I just made a clean installation yesterday. Glad you found a way.

**Comment by W4RH4WK** [comment]
Can I close this issue now?
