### ISSUE TITLE
Should Flash be removed?

### ISSUE THREAD

**Issue by urras** [W4RH4WK/Debloat-Windows-10#12]
Windows 10 comes with Adobe Flash Player built in. Given that Flash is a common source of privacy/security issues, should it be removed in the privacy fix script?

**Comment by maci0** [comment]
Yes its buggy and bloated. flash should be killed off.

**Comment by tumpio** [comment]
Flash is bundled with Edge, so removing it should get rid of flash too. IE11 in the other hand uses system wide (?) flash integration.

This Group policy configures it:
Windows Components\Internet Explorer\Security Features\Add-on Management\
"Turn off Adobe Flash in Internet Explorer and prevent applications from using Internet Explorer technology to instantiate Flash objects"

**Comment by tumpio** [comment]
Found here a solution how to remove the native flash completely:
http://www.nsaneforums.com/topic/202563-uninstalling-windows-81-native-flash/

There is a note that this procedure can be also used to remove other packages as well.
