### ISSUE TITLE
support of other languages

### ISSUE THREAD

**Issue by nacimgoura** [W4RH4WK/Debloat-Windows-10#122]
Hello,
Thank you for your program.
On your readme, it's said that it's only compatible with Windows 10 pro (english).
But have you tested on other languages to say that it was not compatible or not?

Thank you for your reply.

**Comment by W4RH4WK** [comment]
I have not tested it with any other language / version. Most of the things are probably compatible, but you should double check hardcoded paths -- or strings in general -- if you want to use the scripts with a different language.

Hope this helps.

**Comment by nacimgoura** [comment]
Yes thanks.
I will test with windows 10 in french and i will give you feedback on compatibility.

**Comment by nacimgoura** [comment]
Hi,
I tested remove-default-app.ps1 in windows 10 (french) and I work perfectly.

**Comment by W4RH4WK** [comment]
Thank you for the feedback.
