### ISSUE TITLE
Removing apps not working for limited account

### ISSUE THREAD

**Issue by mmikeww** [W4RH4WK/Debloat-Windows-10#131]
So I'm running as a limited user account.

I open an admin powershell prompt as instructed, and I set my execution level. If I run the "remove-default-apps.ps1" script, it does seem to remove the apps, because if I run the script a subsequent time, I get errors that the apps are not found. 

But lets take the "Microsoft.Messaging" app for example. From the same admin powershell prompt, if I try to check if the Messaging app is still available with `Get-AppxPackage *messaging*` I get nothing which would seem to indicate that the app is removed.

However, if I open up the Windows Settings -> Apps, 1) I still see the Messaging app listed, with a greyed out Uninstall button, just like normal. If I then open up a normal non-admin powershell prompt, and run  `Get-AppxPackage *messaging*`  then 2) I **DO** see the Messaging app still available. And similarly, 3) I can press the windows key, type in "messaging" and still run the Messaging app from the start menu. 

But if I then log into my administrator account, the Messaging app is gone with none of the 3 traces in the previous paragraph

Is this script not working if I'm running from a basic limited windows account?

**Comment by mmikeww** [comment]
Similarly, I logged into my Administrator account, and tried to remove the Zune Music/Video (Groove music) apps. They removed correctly from my Administrator account, but then when I logged back into my limited user account, the app was still present there.

So it seems its only removing from the admin account. I guess I'd need to run the script also from my limited account, and with my limited account credentials, but I can't seem to get that to happen.

**Comment by mmikeww** [comment]
Solved it:

> As of v1709 (Fall Creator's Update), there is a new "-AllUsers" flag for Remove-AppxPackage

from

https://social.technet.microsoft.com/Forums/en-US/1d096aa8-924b-484a-ae92-7757e3029198/powershell-script-to-remove-apps-doesnt-work-for-all-users?forum=win10itprosetup

**Comment by W4RH4WK** [comment]
Thanks for letting me know, I'll add that flag to the scripts.

**Comment by mmikeww** [comment]
I guess that fix works for the "removeapps" script. But a lot of the scripts which modify the registry only modify for HKCU current user, so those scripts would need to be run for all users individually.

And yeah already opened PR.

**Comment by W4RH4WK** [comment]
I merged #132 but I did not look into supporting multi-user setups. I close this issue now since it seems to be resolved by your PR.
