### ISSUE TITLE
Help to enable again search in start menu.

### ISSUE THREAD

**Issue by famouzkk** [W4RH4WK/Debloat-Windows-10#136]
I run all files from scripts and also disable-searchUI.bat form utils, i cannot figure out how to start again searchui, any help?|

**Comment by W4RH4WK** [comment]
Navigate to `C:\Windows\SystemApps`. There should be a folder named `Microsoft.Windows.Cortana_cw5n1h2txyewy.bak`. Remove the `.bak` suffix. The searchUI process should start automatically in a few seconds.

**Comment by famouzkk** [comment]
Yeah i analzye bat file and do what u just wrote, so it working again, thanks for help :) 👍

**Comment by koshibb** [comment]
> Navigate to `C:\Windows\SystemApps`. There should be a folder named `Microsoft.Windows.Cortana_cw5n1h2txyewy.bak`. Remove the `.bak` suffix. The SearchUI process should start automatically in a few seconds.
> 
> Edit: Additionally make sure the "Windows Search" service is running. By default, the scripts do not disable it, but double check it anyway.

Hi there - what if there is no folder named that? I am trying to fix the start menu not working (i see the app, but unable to click on it, it doesnt register).
