### ISSUE TITLE
Possible to update for 1709 redstone 3 update?

### ISSUE THREAD

**Issue by waqask64** [W4RH4WK/Debloat-Windows-10#137]
Noticed there were some new apps installed with redstone3. Also the candy crush games come back after a reboot?

**Comment by W4RH4WK** [comment]
Windows installs and configures lots of things with the major updates. I don't think the scripts can configure your system in such a way that settings persist and do not break stuff. My best guess at the moment is to simply run them again and ignore most of the failures.

I haven't looked into why apps keep being reinstalled and by which service...
