### ISSUE TITLE
Disable Performance Monitor Data Collector Sets

### ISSUE THREAD

**Issue by ogmios-voice** [W4RH4WK/Debloat-Windows-10#141]
I would also propose disabling some of the **Performance Monitor** Data Collector Sets. See attachment for details.
[perfmon-disable.ps1.txt](https://github.com/W4RH4WK/Debloat-Windows-10/files/1574016/perfmon-disable.ps1.txt)

**Comment by adicondrache** [comment]
Will this improve performance and fre up some processor, hard drive and memory power?

**Comment by adicondrache** [comment]
I searched on internet about those. But what are those exactly?

**Comment by 4oo4** [comment]
Just curious has anyone else tested this? From doing some reading, it seems that this is pretty safe unless you're actually using Performance Monitor (which I'm guessing most people don't). If I understand right, by default Performance Monitor is creating certain data collections, even if perfmon isn't being used?

**Comment by W4RH4WK** [comment]
I commonly use the performance monitor and think it's a tool some power users are using. I don't really consider this *bloat* so, I'd rather keep this enabled.
