### ISSUE TITLE
install peazip instead of 7zip

### ISSUE THREAD

**Issue by maci0** [W4RH4WK/Debloat-Windows-10#15]
I think peazip should be installed instead of 7zip in https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/install-basic-stuff.ps1

It is a lot better maintained and supports more formats.

**Comment by W4RH4WK** [comment]
Been hearing that a lot lately. Haven't had problems with 7zip but I'll give peazip a try and add it as default if it looks good
