### ISSUE TITLE
Search in Start Menu no longer returns results for newly install programs

### ISSUE THREAD

**Issue by webworker01** [W4RH4WK/Debloat-Windows-10#150]
First, thanks for the great collection of scripts!

After running through them on a new computer, I now notice that new applications that I've installed are no longer shown as results when searching the start menu.  I've tried reindexing search results but it does not seem to help.  Any help would be appreciated as I've come to depend on searching in the start menu as part of my workflow :)

**Comment by tmslnz** [comment]
Background apps toggle needs to be on for this to work under Creators update.
You can toggle individual ones off.

**Comment by webworker01** [comment]
Yes, this was very frustrating to identify. I forgot to close the ticket.

For anyone still searching and running into this problem search in startmenu for "Choose Which Apps can run in the background" and to find the toggle @tmslnz mentions.
