### ISSUE TITLE
Alot of errors (force-mkdir and others)

### ISSUE THREAD

**Issue by pojebunny** [W4RH4WK/Debloat-Windows-10#152]

**Comment by T3rry12** [comment]
run powershell ISE as admin and run this command

Set-ExecutionPolicy -ExecutionPolicy unrestricted

then run the scripts.

**Comment by pojebunny** [comment]
The issue was that I removed everything except for the "scripts" folder.
Because the scripts couldn't access libraries ("lib" folder) I was getting errors that "force mkdir" doesnt exist.

**Comment by W4RH4WK** [comment]
I consider this closed then.
