### ISSUE TITLE
Microsoft Store License Acquisition Error #0x80072EFD

### ISSUE THREAD

**Issue by webworker01** [W4RH4WK/Debloat-Windows-10#154]
Would anyone kindly point me to what scripts should be reverted to allow downloading fro the Windows Store again? I have tried reverting hosts file and disabled services, but something still causing license to not be acquired after running these scripts.

**Comment by allquixotic** [comment]
I removed all the entries starting with `0.0.0.0` in C:\Windows\System32\drivers\etc\hosts (it's a plain text file) and can now access the Windows Store. If you want to remove the minimal entries needed for a working Store you'll have to remove a few at a time until you isolate exactly which entries are causing Store to break.

**Comment by webworker01** [comment]
Thanks 💯 I actually worked that out, forgot about this ticket
