### ISSUE TITLE
Some default apps didn't remove on W10 Pro V1709 build 16299.251

### ISSUE THREAD

**Issue by di57inct** [W4RH4WK/Debloat-Windows-10#158]
Apps such as:

Autodesk Sketchbook
Bubble Witch 3 Saga
Candy Crush Soda Saga
Disney Magic Kingdoms
Dolby Access
March of Empires: War of Lords
Mixed Reality Portal
Mixed Reality Viewer
MSN News
Paint 3D
Sticky Notes

didn't properly remove.

Maybe they are new default apps that come with the new version/build?
Please add them to the list if possible. I can offer TeamViewer access if needed.

**Comment by Kizoky** [comment]
+1 confirm
Some apps hasn't been removed even with a fresh install of Windows 10

**Comment by seyoum** [comment]
I just downloaded the latest script and checked that **Bubble Witch 3 Saga** is still not in the script, shich it really should. The other mentioned apps are present 😸

**Comment by ddd111ddd** [comment]
I'm starting to think it's easier to remove all apps except the ones you whitelist. Microsoft is in love with garbage apps.

**Comment by W4RH4WK** [comment]
I merged some pull requests, so more apps should get removed now. Please provide me the identifier so I can add it the apps to the list.

**Comment by cbaldan** [comment]
I have been using the scripts for a few months and I see those apps listed being successfully removed.
Perhaps you can close this ticket @W4RH4WK ?

**Comment by W4RH4WK** [comment]
Sure thing.
