### ISSUE TITLE
Some host names are redundant

### ISSUE THREAD

**Issue by maximmasiutin** [W4RH4WK/Debloat-Windows-10#159]
The following hostnames are redundant since they are not used directly but are results of resolution of main hosts. There is no reason to list them since there are too many of them and they are volatile. Here are the redunant hosts:

0.0.0.0 184-86-53-99.deploy.static.akamaitechnologies.com
0.0.0.0 a1621.g.akamai.net
0.0.0.0 a1856.g2.akamai.net
0.0.0.0 a1961.g.akamai.net
0.0.0.0 a978.i6g1.akamai.net
0.0.0.0 az361816.vo.msecnd.net
0.0.0.0 az512334.vo.msecnd.net
0.0.0.0 cds26.ams9.msecn.net
0.0.0.0 cs1.wpc.v0cdn.net
0.0.0.0 db3aqu.atdmt.com
0.0.0.0 e2835.dspb.akamaiedge.net
0.0.0.0 e7341.g.akamaiedge.net
0.0.0.0 e7502.ce.akamaiedge.net
0.0.0.0 e8218.ce.akamaiedge.net
0.0.0.0 msnbot-65-55-108-23.search.msn.com

One line even contains an error:

0.0.0.0 telemetry.appex.bing.net:443

(the ":443" prefix is not used in the "hosts").

**Comment by gxgl** [comment]
That's write. The host file could not be used to block access on ports. You need to use firewall for that. From powershell and cmd we have netsh.

**Comment by W4RH4WK** [comment]
Thanks for pointing out that faulty line. Regarding the Akamai related hosts, is there are problem with keeping them? So far there seems to be only one which actually breaks stuff.

**Comment by maximmasiutin** [comment]
It's up to you to decide.

**Comment by W4RH4WK** [comment]
I'll leave it as it is for now, until problems start to arise. Thank you for the input.

**Comment by isaak654** [comment]
I had to remove all akamai entries from hosts file because firefox 72.0.2 tried to update the Widevine content decryption plugin without success. Now I can watch a live streaming TV channel without any sort of lag.

**Comment by W4RH4WK** [comment]
@isaak654 Thank for letting us know. If I find the time, i'll add a comment to the corresponding lines.
