### ISSUE TITLE
Uninstalling OneDrive breaks File History and Backup

### ISSUE THREAD

**Issue by aramboi** [W4RH4WK/Debloat-Windows-10#16]
Uninstalling OneDrive causes the `Backup` functionality under `Settings -> Update & Security` to complain that `fhmanagew.exe` is not accessible.

<img width="421" alt="backup-error" src="https://cloud.githubusercontent.com/assets/12439/9369003/d976b632-46c6-11e5-83a9-eb7a2d23eea9.PNG">

More info on the file here: https://msdn.microsoft.com/en-us/library/hh829770%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

Env: Windows 10 Home x64 (upgraded from 8.1)

**Comment by aramboi** [comment]
Seems the issue can be solved by turning the `Backup` `OFF` and `ON` again. :smile:

**Comment by W4RH4WK** [comment]
Maybe I can prevent this error message by stopping an starting the backup service in the script.

**Comment by W4RH4WK** [comment]
Are you sure that this is caused by the `remove-onedrive.ps1` script. It does not seem to be reproducible. Note that I have no backup configured.

**Comment by aramboi** [comment]
I had the backup set up before running the script, ran the script and then the backup would complain. Unfortunately I don't have a win10 vm setup and there is no standalone installer for OneDrive for win10 (only 7/8) to do it on my machine.

I was in the process of getting a win10 vm up and running for debugging this stuff anyway, because running these scripts on my actual machine is not really the best thing to do. :P

**Comment by W4RH4WK** [comment]
I encourage people to reboot their system after running the scripts. So even though this bug may be reproducible (with a setup backup) I'd rather have people reboot afterwards instead of restarting selected services.

**Comment by aramboi** [comment]
I rebooted after running the script, so probably just reinitializing (not only restarting the process) the backup would make this work again.

I am downloading the Win10 ISO now to set up a VM and try to reproduce this again with more accurate steps.

**Comment by W4RH4WK** [comment]
okay, thanks

**Comment by aramboi** [comment]
Managed to get a VM with clean Home edition up and running, but I could not reproduce the issue with the latest `remove-onedrive.ps1` script. It might have been a fluke on my local machine. I think it's safe to close this unless anyone else has this issue in the future.

**Comment by W4RH4WK** [comment]
closing this for now, time will tell
