### ISSUE TITLE
(April 2018 Update) block-telemetry.ps1 hosts causes Windows Update to falsely claim that there are no updates available

### ISSUE THREAD

**Issue by asdfbuiaskdf** [W4RH4WK/Debloat-Windows-10#160]
One of the hostnames blocked through block-telemetry.ps1 causes Windows Update to claim that "You're up to date", even though there's a Cumulative Update available.
Can't help you with the troublesome entry as I have no idea how to debug the hosts file under Windows.

- Install a fresh copy of Windows 10 April 2018 Update (1803)
- Apply block-telemetry.ps1
- Open Windows Update and check for updates

In my case it successfully finds and installs the latest Malicious Software Removal Tool and Windows Defender definitions.
However, the 2018-05 Cumulative Update won't ever show up.

- Empty the hosts file
- Flush DNS cache

Now the Cumulative Update will get detected and installed.

![output](https://user-images.githubusercontent.com/39127588/39818778-f885c5b4-53a1-11e8-8d20-3a68a475c670.gif)

**Comment by n3oney** [comment]
Additionally: it breaks Windows Insider Program too. If you want to start, it says it can't connect.

**Comment by dzaikos** [comment]
According to [Microsoft's web site](https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1803-endpoints#settings) if you block `settings-win.data.microsoft.com` the Insider Program won't work. This domain is added to the hosts file when [blocking Telemetry](https://github.com/W4RH4WK/Debloat-Windows-10/blob/cc3f0f7ca2b4597143682e45390a99c1e9cd5d38/scripts/block-telemetry.ps1#L108).

**Comment by W4RH4WK** [comment]
@dzaikos thank you. This domain is no longer blocked by default.

**Comment by W4RH4WK** [comment]
@asdfbuiaskdf can you please remove `settings-win.data.microsoft.com` from the blocked domains and check whether this resolves the issue.
