### ISSUE TITLE
Reverse Effects of Block Telemetry

### ISSUE THREAD

**Issue by Erdyke** [W4RH4WK/Debloat-Windows-10#161]
I was using the block telemetry scripts on a couple new Win10 installs and realized the block-telemetry scripts did more than I wanted. 

In the case anyone blocks a domain they didn't mean to, you need to go look in: `C:\Windows\System32\drivers\etc\hosts`  and remove the line with the domain name you wish to unlock.

**Comment by W4RH4WK** [comment]
In addition to this, note that some IPs are blocked via a firewall rule.
