### ISSUE TITLE
Re-enable Windows Defender

### ISSUE THREAD

**Issue by Erdyke** [W4RH4WK/Debloat-Windows-10#162]
Ran disable-windows-defender.ps1

I figured I'd be able to re-enable from gui or with an windows update.  Guess I got ahead of myself and was naive on the ultimate effect of this script.  Any suggestions on how to reverse?

**Comment by W4RH4WK** [comment]
Hey there, sorry for the late reply. Try the following:

- download and extract the [Sysinternals Suite](https://docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite)
- reboot into safe-mode
- start `Autoruns64.exe` (with administrator privileges)
- under *Options* disable *Hide Microsoft Entries* as well as *Hide Windows Entries*
- filter for *defender*
- check everything that is listed
- reboot

Now Windows Defender should be up and running as usual.

**Comment by adjajdsfj** [comment]
tell me please how turn off this code? i want to use defender, please tell me)
