### ISSUE TITLE
How to use these scripts in a Windows Domain

### ISSUE THREAD

**Issue by code-chicken** [W4RH4WK/Debloat-Windows-10#167]
Hi all,

maybe someone can put me in the right direction: I want to use this scripts in a domain, so that all W10-computers joined to this domain will be debloated.

I thought about Group Policies, but I am not sure how to implement this with these scripts.

Maybe someone can help?

Thank you in advance!

**Comment by delirium26** [comment]
Hello,
Maybe it will work:

1. Unzip and upload Debloat-Windows-10-master to the share in your network. For example \\\server\share\Debloat-Windows-10-master\

2. Create bat file Debloat-Windows-10-master\scripts\run.bat
```
Powershell.exe -executionpolicy remotesigned -File %~dp0\block-telemetry.ps1
Powershell.exe -executionpolicy remotesigned -File %~dp0\disable-services.ps1
Powershell.exe -executionpolicy remotesigned -File %~dp0\fix-privacy-settings.ps1
Powershell.exe -executionpolicy remotesigned -File %~dp0\optimize-user-interface.ps1
Powershell.exe -executionpolicy remotesigned -File %~dp0\optimize-windows-update.ps1
Powershell.exe -executionpolicy remotesigned -File %~dp0\remove-default-apps.ps1
Powershell.exe -executionpolicy remotesigned -File %~dp0\remove-onedrive.ps1
```
It will help you later to run all needed scripts with one line. It is just example, so you freely can add or delete needed lines.

3. With GPO add scheduled task with needed triggers to your Windows 10 PCs, where put something like this:
`net use G: \\server\share\Debloat-Windows-10-master\ && G:\scripts\run.bat`
Don't forget run this task with appropriate system rights.

I'm going to check this method soon and report the results.

**Comment by W4RH4WK** [comment]
@code-chicken is this resolved?
