### ISSUE TITLE
Not Working/Partial Working with SCCM OSD Task Sequence

### ISSUE THREAD

**Issue by ruiqiu** [W4RH4WK/Debloat-Windows-10#170]
Hi, 

I have tried the script inside Windows, and it works perfect.
However when I add this script during OSD Task Sequence(inside Windows PE), sometimes it can remove part of the bloat software, sometimes it won't remove them all all.

**Comment by Gluconda** [comment]
Same experience as myself...some of the apps are removed while others remain.

Any suggestions?

Thanks,

**Comment by frankk74** [comment]
Someone has else had approached this from the SSCM side of the house here: 

Https://www.scconfigmgr.com/2018/05/13/remove-built-in-apps-for-windows-10-version-1803/

Also he has some additional items that can be removed such as:

"Microsoft.HEIFImageExtension",
 "Microsoft.VP9VideoExtensions",
 "Microsoft.WebMediaExtensions",
 "Microsoft.WebpImageExtension"

I hope this helps...

**Comment by W4RH4WK** [comment]
If there is an easy fix to make the scripts work with SSCM please open a pull-request.

So far, using SSCM is not officially supported by me as I lack the infrastructure (and time) for testing.
