### ISSUE TITLE
Scripts prevent login to anything microsoft

### ISSUE THREAD

**Issue by H-Park** [W4RH4WK/Debloat-Windows-10#171]
I ran these scripts on a new laptop, and every login.live.com (microsoft's login handling website) returns a 404. 

This is by block-telemetry.ps1's design. 

To remove this blockage, simply remove line 193 - "login.live.com""

Scripts work great otherwise!

**Comment by W4RH4WK** [comment]
`login.live.com` is no longer blocked by default. See #181.
