### ISSUE TITLE
Store broken after running scripts

### ISSUE THREAD

**Issue by Devo0** [W4RH4WK/Debloat-Windows-10#173]
After running the scripts, Windows Store won't load anymore with the remark:
"Microsoft store needs to be online. It looks like you're not" with an error  0x80072EE7

Assuming this is one of the privacy or telemetry settings, can someone figure out which so this can be commented out?

**Comment by rickythefox** [comment]
Remove the blocks in your hosts file, that should fix the issue. You can put them back once you are done with the store.

**Comment by Dioxaz** [comment]
Commenting out only the "storeedgefd.dsx.mp.microsoft.com" in the host files seems to do the trick. I didn't do any extensive tests yet however. I tried downloading one app and it seemed to work.

Also, for those having problems creating new local accounts ("an error occured, try later blah blah"), comment out all the last lines relating to Skype in your host file:

apps.skype.com
c.msn.com
login.live.com
pricelist.skype.com
s.gateway.messenger.live.com
ui.skype.com

It might be that only the "login.live.com" has to be commented out, as I've read somewhere that Windows 10 still queries some Windows Live servers even when you chose to create a local account (non-Microsoft one).

**Comment by IBaydenI** [comment]
Had the same issue. This fixed it, thanks!

**Comment by W4RH4WK** [comment]
Is this resolved?

**Comment by Devo0** [comment]
Yeah, this fixed it. Haven't looked at it since... So I forgot to set it as
resolved.
