### ISSUE TITLE
Is there a way to bring back apps that has been removed using this script? 

### ISSUE THREAD

**Issue by ndmarkley** [W4RH4WK/Debloat-Windows-10#174]
Hi: 

I am trying to reinstall, and get the Windows Store back on the computer after running this script. Is there a way to bring back apps that has been removed using this script? 
OR Do I have to do windows repair or reformat again. 
Thank you for your help. 
-Nathan

**Comment by antixcode6** [comment]
Hello, 

This is an old comment, but in case you have not gotten your answer yet you can use the PS modules

Get-AppxPackage to get the name of a package you're missing, and then use Add-AppxPackage to re-add. 

So, for the windows store do the following

`Get-AppxPackage -allusers Microsoft.WindowsStore | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}`

You can use `Get-AppxPackage | More` to view all packages with status information etc. 

Hopefully this answers your question.

**Comment by W4RH4WK** [comment]
@ndmarkley is this resolved?
