### ISSUE TITLE
windows broken

### ISSUE THREAD

**Issue by PixelNotFound** [W4RH4WK/Debloat-Windows-10#177]
Hi there,
I installed your scripts but now i cant install windows updates, switch to insider builds or use cortana. How can i delete your script and make everything work again? Or do you have a other soluition

**Comment by W4RH4WK** [comment]
Closing this, since no response from OP. Please note the following paragraph of the README:

> There is no undo, I recommend only using these scripts on a fresh installation (including Windows Updates). Test everything after running them before doing anything else. Also there is no guarantee that everything will work after future updates since I cannot predict what Microsoft will do next.
