### ISSUE TITLE
its a question only

### ISSUE THREAD

**Issue by Michaelvx** [W4RH4WK/Debloat-Windows-10#187]
how can i make sure its safe to use with no infection im sorry for asking this but i'm little worried
and also i dont want to disable the windows defender
thanks in advance

**Comment by W4RH4WK** [comment]
Compare to other project chasing the same goal, debloating Windows 10, this here is just a collection of PowerShell scripts. Rather than downloading and blindly running a pre-built executable you can download the scripts and investigate them, line by line.

Simply remove the things you don't want.
