### ISSUE TITLE
Fingerprint Reader stopped working after running disable-services.ps1

### ISSUE THREAD

**Issue by ducviet321** [W4RH4WK/Debloat-Windows-10#189]
Hello everyone,

The disable-services.ps1 script disable "WbioSrvc" (Windows Biometric Service) which is used for fingerprint reader or facial dectector. 

I think there should be a warning before running this because it took me hours to figure out why my laptop stop recognize me.

Thank you,
Viet

**Comment by W4RH4WK** [comment]
I extended the comment beside *WbioSrvc* and added a note to the README's *known issues* section. I won't add a warning before the script is executed as they are non-interactive by design.

Aside from that, I strongly discourage the use of biometrics for authentication in any way, shape, or form.
