### ISSUE TITLE
fix-privacy-settings.ps1 - How to enable mobile hotspot again?

### ISSUE THREAD

**Issue by sadmachine31** [W4RH4WK/Debloat-Windows-10#190]
fix-privacy-settings.ps1

```
Write-Output "Do not share wifi networks"
$user = New-Object System.Security.Principal.NTAccount($env:UserName)
$sid = $user.Translate([System.Security.Principal.SecurityIdentifier]).value
force-mkdir ("HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features\" + $sid)
Set-ItemProperty ("HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features\" + $sid) "FeatureStates" 0x33c
Set-ItemProperty "HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features" "WiFiSenseCredShared" 0
Set-ItemProperty "HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features" "WiFiSenseOpen" 0
```

Thanks

**Comment by W4RH4WK** [comment]
Your problem is that after running the scripts, mobile hotspot does no longer work?

Is this right? Which scripts did you run? Have you made any modifications to them?

**Comment by sadmachine31** [comment]
I need the windows 10 mobile hotspot feature but
I executed the "fix-privacy-settings.ps1" without even read what's in it, my bad.  Can you help me?

I'm pretty sure these lines of code did it :

```
> Write-Output "Do not share wifi networks"
> $user = New-Object System.Security.Principal.NTAccount($env:UserName)
> $sid = $user.Translate([System.Security.Principal.SecurityIdentifier]).value
> force-mkdir ("HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features\" + $sid)
> Set-ItemProperty ("HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features\" + $sid) "FeatureStates" 0x33c
> Set-ItemProperty "HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features" "WiFiSenseCredShared" 0
> Set-ItemProperty "HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features" "WiFiSenseOpen" 0
```

I tried to enable it back by modifying the zeros to the opposite as 'enable' like this : 
```
> Set-ItemProperty "HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features" "WiFiSenseCredShared" 1
> Set-ItemProperty "HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features" "WiFiSenseOpen" 1
```
Now the mobile hotspot can be turned on, but devices won't connect. I think there's something to do with this line of code : 

> `> Set-ItemProperty ("HKLM:\SOFTWARE\Microsoft\WcmSvc\wifinetworkmanager\features\" + $sid) "FeatureStates" 0x33c`

What can i do with this one? Sorry for bothering, thanks.
And also thanks for the great work, my windows experience now much smoother than before.

**Comment by W4RH4WK** [comment]
Okay, try changing this key to `0x13c` which is the default.

**Comment by sadmachine31** [comment]
I tried to do as what you said, it's still the same. Hotspot turned on but devices won't connect.
Thank you for your respond, i know this is my fault. I read your thread disclaimer that there is no undo, but i'm reckless anyway.

**Comment by W4RH4WK** [comment]
Looking at the script, there is only one other section I'd associate with your problem. The one about *disabling information sharing between unpaired devices*.

Looking at my local installation where I didn't use the scripts: Backup everything inside `HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeviceAccess` and remove the `DeviceAccess` folder. Reboot and try again.

Otherwise I am out of ideas.

**Comment by W4RH4WK** [comment]
Is this resolved? Or should I leave it open?

**Comment by sadmachine31** [comment]
Reinstalled windows 10, fixed.
I think there is no undo in that script, just warn ppl to read what the script do. So reckless ppl like me won't "accidentally" disable hotspot tethering permanently.

Thanks for your support!
