### ISSUE TITLE
No script to undo any changes made by the debloating scripts

### ISSUE THREAD

**Issue by TimmSkiller** [W4RH4WK/Debloat-Windows-10#191]
It would be great if there would be a script (or a folder) of similar scripts, that do exactly the opposite, reverting the changes made. For example, I have chosen to disable Windows Defender, but SmartScreen is still running, preventing me from running anything third-party. Normally I would've been able to exclude the application that it would'nt let me run. Now I can't run those apps. Thanks

**Comment by W4RH4WK** [comment]
I won't be adding any undo scripts.

The first reason is that it is only recommended to use these scripts on a fresh installation of Windows. If they mess up your system in any way, simply reinstall. Second, restoring the previous state *exactly* as it was, may be impossible for some operations done by the scripts.

If you are looking for a solution, which can be applied to an existing (not fresh) installation, which also provides undo mechanisms, this project is not for you.
