### ISSUE TITLE
bluetooth completely disabled

### ISSUE THREAD

**Issue by mustypits** [W4RH4WK/Debloat-Windows-10#193]
if this is supposed to happen , can anyone assist in re-enabling it?

**Comment by W4RH4WK** [comment]
Try re-enabling services disabled by `disable-services.ps1`.

**Comment by SparrowOchon** [comment]
What script did you run for this to happen?

**Comment by mustypits** [comment]
It's all fine now. It reappeared after a few days.

**Comment by W4RH4WK** [comment]
@mustypits can I close this?
