### ISSUE TITLE
Can I use this on my Windows 10 Home Single Language?

### ISSUE THREAD

**Issue by 5ervant** [W4RH4WK/Debloat-Windows-10#194]
I updated my device multiple times *(my current version is 1803)* and have connected my Microsoft account on it. My edition is Windows 10 Home Single Language.

Can I use this to debloat my device?
Any recommended alternatives that best suits on my situation?
Thanks!

**Comment by W4RH4WK** [comment]
Well, it is recommended that you only run these scripts on a fresh installation, so if it messes up something, simply reinstall. With this in mind, it shouldn't be a problem to try them.

As for an alternative, check out this: https://github.com/10se1ucgo/DisableWinTracking
