### ISSUE TITLE
Windows store is missing - unable to re-install it

### ISSUE THREAD

**Issue by mitrovic3** [W4RH4WK/Debloat-Windows-10#197]
Hi There

I am having same problem on 3 different computers.

After fresh installation of the win 10, I run your script and everything looks great on my main user account. Once i added 2nd user account Windows store was missing and there is no way to restore it. Same happen with every new account and i literally try everything.

Even posted questions here:
https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_store/windows-store-is-missing-windows-debloater-script/86f5b0f7-a21a-4d6b-a90a-a06974b184b2?messageId=011f9c13-2b2f-416e-8f89-87517c5fb483

Weirdest part is, on my main user account, store is still there, it is working and i can use it.

Any idea how to fix it?

Thanks,
Neb

**Comment by W4RH4WK** [comment]
Unfortunately no. I ran into the same problem where I could not get the Windows Store working again. I think the only option right now is to reinstall.

I'll add a note to the corresponding line in the scripts.

**Comment by diorcety** [comment]
I was in the same situation: Copy / Paste from a "good" computer C:\Program Files\WindowsApps\Microsoft.WindowsStore* and run this kind of command in powershell Add-AppxPackage-register"C:\Program Files\WindowsApps\Microsoft.WindowsStore_XXXXX_x64
_8wekyb3d8bbwe\AppxManifest.xml"-DisableDevelopmentMode
