### ISSUE TITLE
Windows 10 apps can't be installed

### ISSUE THREAD

**Issue by DavidUnknown** [W4RH4WK/Debloat-Windows-10#204]
Well, basically, with this debloat, the firewall is turned off, no problem with that.
The only problem I had, is that i can't find a way to install apps from the store
I mean, there are some really useful apps in the windows 10 store that i need, (not like the preinstalled ones) and i can't find a way to make windows stop needing the goddamn firewall
Help pls
![image](https://user-images.githubusercontent.com/37724998/59167823-6b63d680-8af0-11e9-873a-ff6eee61677a.png) (my native language is spanish but i can barely handle the english) There it is the error code

**Comment by W4RH4WK** [comment]
> firewall is turned off

To be specific, I think you are referring to the Windows Defender. The *firewall* is not disabled by these scripts, on the contrary some IPs are blocked with the firewall.

If Windows Defender is disabled, turn it back on. I ran into the same problem where the Windows Store was unable to install apps because of it being disabled.

Furthermore, disable the corresponding block rule in the firewall settings and comment out domain redirects in the hosts file. These are the most likely culprits of such an issue.

**Comment by DavidUnknown** [comment]
How do I enable defender again? Otherwise, I tried to install the .appx package from the powershell and I didn't get to install it bc it says "Firewall is disabled, please turn it on and try again"
The error code says something like that too

**Comment by W4RH4WK** [comment]
Disable the corresponding group policy entries and enable the Windows Defender related services. Just the reverse of what the script did.

**Comment by DavidUnknown** [comment]
I'm not skilled enough with this to reverse that type of script... Can u help me?

**Comment by W4RH4WK** [comment]
No, I don't have the time to hold your hand here. You should be able to push through with the information I provided. Just lookup the things you don't know how to do. As an alternative, simply reinstall your system and do not use the scripts.

Let me quote the first section of the README:

> These scripts are intended for tech-savvy administrators, who know what they are doing and just want to automate this phase of their setup. If this profile does not fit you, I recommend using a different (more interactive) tool -- and there are a lot of them out there.
>
> There is no undo, I recommend only using these scripts on a fresh installation (including Windows Updates). Test everything after running them before doing anything else. Also there is no guarantee that everything will work after future updates since I cannot predict what Microsoft will do next.
