### ISSUE TITLE
PS> Set-ExecutionPolicy Unrestricted don't work

### ISSUE THREAD

**Issue by moulin-louis** [W4RH4WK/Debloat-Windows-10#205]
Hello, i'm on windows 1903 and when i execute PS> Set-ExecutionPolicy Unrestricted in powershell with admin rigths and in the folders scripts, i have this :
PS> : The term "PS>" is not recognized as a applet name, function, script file, or program
executable. Check the spelling of the name, or if a path exists, verify that the path is correct
and try again.
To the line character: 1: 1
+ PS> Set-ExecutionPolicy Unrestricted
+ ~~~
    + CategoryInfo: ObjectNotFound: (PS>: String) [], CommandNotFoundException
    + FullyQualifiedErrorId: CommandNotFoundException

Anibody have a solutions ? Thanks
(Sorry for my english, i'm french)

**Comment by alenmeister** [comment]
How about you try and not type in PS>?! That’s only a statement to show that it’s a PowerShell command. Also, if you couldn’t figure that out. I’d be careful about running these scripts...

**Comment by moulin-louis** [comment]
oooh, I am rather stupid and an beginner. Thanks for the help !

**Comment by W4RH4WK** [comment]
> oooh, I am rather stupid and an beginner. Thanks for the help !

Just to clarify, you have read this section of the README.

>These scripts are intended for tech-savvy administrators, who know what they are doing and just want to automate this phase of their setup. If this profile does not fit you, I recommend using a different (more interactive) tool -- and there are a lot of them out there.
