### ISSUE TITLE
Add jobs to scripts.

### ISSUE THREAD

**Issue by SparrowOchon** [W4RH4WK/Debloat-Windows-10#206]
When looking through the script I noticed there's no jobs being started I.e this is single threaded. Adding threads would allow many of the jobs to execute faster as we can run multiple instances at the same time. E.x disabling services we could in turn disable 3 at a time instead of one or more depending on the users computer specs. 
<br><br>
I've written a script for windows 7 that removes bloat and uses threads which you can find here [script](https://gitlab.com/SparrowOchon/win7cleaner). Which is what a threaded win10 debloater would look like.
<br><br>
Would this be something you would be interesting in adding? If so we would also have to restructure sections of code to avoid it becoming to complex.

**Comment by W4RH4WK** [comment]
Hey there, thanks for the input. No, I am not interested in this. I don't see a performance issue with the scripts as of right now and converting them to operate in parallel may introduce additional bugs and decrease readability.

**Comment by SparrowOchon** [comment]
Thats fair in term of speed, I was planing on adding update hiding and blocking for known telemetry updates which would have benefited from it. As for readability I dont fully agree with it being decreased but it might push away some new contributors.<br>

Great work with these scripts BTW.

**Comment by W4RH4WK** [comment]
Thank you.
