### ISSUE TITLE
Remove "Xbox Gaming Services"

### ISSUE THREAD

**Issue by Ryanjtombs** [W4RH4WK/Debloat-Windows-10#208]
Could the remove default apps script be updated to include this? Seems to be a new app for 1903... 

https://www.microsoft.com/en-us/p/gaming-services/9mwpm2cqnlhn

**Comment by W4RH4WK** [comment]
Done, let's see if this breaks something in the future.

Please note that I currently don't have the time to test this. I am still on an older Windows version, hence unable to install this app anyway.

**Comment by Samisaprogrammer** [comment]
This broke everything and now people can't log into xbox. I think you should revert this change.
