### ISSUE TITLE
minecraft delted 

### ISSUE THREAD

**Issue by MrPotatoBob** [W4RH4WK/Debloat-Windows-10#212]
minecraft windows 10 edition (the uwp from windows store) was delted with remove defualt apps i dont know if this does this to other uwp games but all good il just reinstall it

**Comment by MrPotatoBob** [comment]
also delted most of my normal uwp apps just know youl have to reinstall them

**Comment by W4RH4WK** [comment]
`remove-default-apps.ps1` contains the list of all apps that are removed. Their identifier is self explanatory in most cases.

**Comment by LucasMZReal** [comment]
Minecraft Bedrock Edition was removed cause the "company" that makes it is Microsoft. And the rest of the "default-apps" use Microsoft too.
![image](https://user-images.githubusercontent.com/55422065/65834346-5b931c80-e2b0-11e9-8368-4ca73b60890d.png)
