### ISSUE TITLE
Hmm, rundll32.exe corrupted?

### ISSUE THREAD

**Issue by LucasMZReal** [W4RH4WK/Debloat-Windows-10#214]
Okay, so I debloated Windows 10 and I was gonna play some games, okay and then I was gonna change my resolution to 800x600 cause my PC struggles with my native resolution and change also the Hz from 60 to 75 and I see this;
![image](https://user-images.githubusercontent.com/55422065/65007750-6e374a00-d8dd-11e9-96da-67fe402e60ed.png)
I'm brazilian so the language in the picture is all in portuguese, but I was researching, and looks like the error comes out as "Windows cannot access the specified device, path or file. You may not have appropriate permissions to access the item." in the ### English language, can you guys help me?

**Comment by LucasMZReal** [comment]
oMG i RESTARTED MY COMPUTER AND IT WORKED OMG WILL CLOSE THIS SOWWY

**Comment by W4RH4WK** [comment]
Good that you were able to resolve the issue. No part of the script touches `rundll32.exe`, so I suspect the culprit to be something else. But nevertheless, thank you for opening an issue right away.
