### ISSUE TITLE
Can't log in with XBOX cause XBOX is missing.

### ISSUE THREAD

**Issue by LucasMZReal** [W4RH4WK/Debloat-Windows-10#215]
Now, I know that the "remove-default-apps.ps1" removes the XBOX app, but is THERE ANY WAY to recover the XBOX APP, so I can log in with XBOX?

**Comment by W4RH4WK** [comment]
Have you tried the `Add-AppxPackage` command?

**Comment by LucasMZReal** [comment]
Can you send me it to me? I'm not a "professional" in powershell or cmd.

**Comment by W4RH4WK** [comment]
Than you shouldn't have used the scripts in the first place. It is stated in the README that it is intended for tech savvy people. In this case I recommend wiping the machine and reinstalling Windows, and not using these scripts. See README for other, similar, more user-friendly tools.

**Comment by LucasMZReal** [comment]
i t   d o e s n ' t   h u r t
