### ISSUE TITLE
A few questions from a confused newbie..

### ISSUE THREAD

**Issue by hosadokha** [W4RH4WK/Debloat-Windows-10#218]
I have to say the directions u provided are not newb friendly at all..
1-While reading your Readme.md number 3 under Usage it says "Run the scripts from Powershell" np at all, except there are three folders in your package "scripts", "lib", "utils". so if i run the files in the scripts folder, what do i do with the other folders? :s 
2-your method uses Powershell to remove default windows programs but what about Dism.exe? what is the difference between the two methods?
3-I am also a bit confused  whether Windows Update depends on Edge & IE and the Google isnt helping.. can I completely remove Edge & IE without consequences?.. I know this issue may not directly relate to your scripts, but im sure u can help me ;)

**Comment by W4RH4WK** [comment]
First of all: this is intended, the README stats:

> These scripts are intended for tech-savvy administrators, who know what they are doing and just want to automate this phase of their setup.

1: `lib` contains functionality that is automatically used by the scripts, i.e. the scripts are not self-contained. `utils` contain additional tweaks that are not the focus of this project, but you (as a system administrator) my find interesting.

2: `dism.exe` is much more low-level, while this allows you to remove even more stuff, it's also very like to break something. Using PowerShell's `Remove-AppxPackage` is *safer*.

3: I'd recommend not removing Edge & IE, unless you have a specific reason for it.

Please also note that it is only recommended to use these scripts on a fresh install, and that you test your setup thoroughly before using it for production.

**Comment by hosadokha** [comment]
Thank you.. this is much appreciated  @W4RH4WK  :)  :)  :+1:
