### ISSUE TITLE
Link to download seems broken?

### ISSUE THREAD

**Issue by Ud4ba** [W4RH4WK/Debloat-Windows-10#219]
I cant connect to the link of the download

edit : i get this error : 504 Gateway Time-out

**Comment by Pibacco** [comment]
https://codeload.github.com/W4RH4WK/Debloat-Windows-10/zip/master?
No, I just used it, it's working.

**Comment by W4RH4WK** [comment]
This would be the *official* download link: https://github.com/W4RH4WK/Debloat-Windows-10/archive/master.zip
