### ISSUE TITLE
Twitter login doesn't work as intended

### ISSUE THREAD

**Issue by isaak654** [W4RH4WK/Debloat-Windows-10#224]
Problem:
I'm unable to remember Twitter login permanently because every time I close Firefox or MS Edge it will disconnect itself.
This breaks the purpose of 'remember me' checkbox in the login page.

Cause:
two specific entries in block-telemetry.ps1: 
static.ads-twitter.com
p.static.ads-twitter.com

Solution:
comment or remove those entries.

**Comment by W4RH4WK** [comment]
Thank you for the input. I'll mark the corresponding lines in with comments.
