### ISSUE TITLE
Can't play Xbox linked games after running script

### ISSUE THREAD

**Issue by Samisaprogrammer** [W4RH4WK/Debloat-Windows-10#231]
Hey! So I had just run this script and can't seem to run Minecraft after it. Well, I can run the game but I can't login to Microsoft, and also windows store works fine and so does windows itself but even the Xbox insider app and the Xbox (beta) app can't login to Microsoft. If anyone knows how to fix it I'd be glad to know!
![Xbox insider hub Error](https://user-images.githubusercontent.com/59611020/73653024-4c810880-46ae-11ea-945a-efc32f6181a5.jpg)
![Minecraft Error](https://user-images.githubusercontent.com/59611020/73653040-53a81680-46ae-11ea-9fa3-96981a8a777b.jpg)

**Comment by W4RH4WK** [comment]
Please try reinstalling the `Microsoft.GamingServices` app.

https://www.microsoft.com/store/productId/9MWPM2CQNLHN

**Comment by cbaldan** [comment]
It sort of makes sense that all XBox related services stop working, give the scripts strip all of them out of Windows 10.

**Comment by W4RH4WK** [comment]
Please note that I reverted fdcba03 as this would introduce inconsistency as other xbox related services still get removed. So, the `Microsoft.GamingServices` will be removed by default.

I added a note to the README stating that people who want to use their system for gaming should adjust the scripts accordingly.

Furthermore, I assume that reinstalling the mentioned app (and re-enabling related services) fixed this issue.
