### ISSUE TITLE
Compatibility with Windows Insider Program (e.g. to install WSL2)

### ISSUE THREAD

**Issue by neriglissar** [W4RH4WK/Debloat-Windows-10#233]
Hi all, I am creating this issue because many of you might want to use the Windows Insider Program to install preview builds of Windows. With a preview build, you can for instance [install the second version of WSL](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install) (Windows Subsystem for Linux) which has many great features. However, these scripts break access to the Windows Insider Program.

For one thing, the lines
`"insiderservice.microsoft.com"`
`"insiderservice.trafficmanager.net"`
in [block-telemetry.ps1](https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/block-telemetry.ps1) should be commented in order to connect to the service in Windows Insider Program Settings. 

Further, the lines
`force-mkdir "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection"`
`Set-ItemProperty "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" "AllowTelemetry" 0`

should not be executed if you want to upgrade to a preview build, because this needs diagnostics settings set to full. I used [this method](https://www.techjunkie.com/some-settings-are-managed-by-your-organization-windows-10/) revert the setting so I could set it to Full diagonistics and install a preview build. 

If the above alone is not enough, possibly one has to revert [disable-services.ps1](https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/disable-services.ps1
) for the settings
`"diagnosticshub.standardcollector.service" # Microsoft (R) Diagnostics Hub Standard Collector Service`
`"DiagTrack"                                # Diagnostics Tracking Service`
but I am not sure about this.

Hope this is of help to anyone.

**Comment by W4RH4WK** [comment]
Hey there. Thanks for the detailed description.

Just for clarification: This project does not support the insider program. It's already hard enough to keep track of changes happening in the regular stable channel. Furthermore, I think that this project directly conflicts with the insider program. If you gonna join the insider program to access preview features, you should keep telemetry enabled anyway. That's the whole point of the insider program.
