### ISSUE TITLE
Xbox games Sign in error

### ISSUE THREAD

**Issue by michael200013** [W4RH4WK/Debloat-Windows-10#234]
After doing the debloat all my windows store games no longer can sign in and i cant play any of them
like forza horizon 4, Halo MC, and others also noticed that the xbox app no longer can sign in also i press sign in and a blank black square apears for a second and closes. there no way i cant play my games i purchced even tried to reinstall xbox game app and nothing here i have some images of the issue.
![Captura de pantalla (4192)](https://user-images.githubusercontent.com/56094749/75817813-cc5dc980-5d65-11ea-93a7-848a0fde52a2.png)
![Captura de pantalla (4190)](https://user-images.githubusercontent.com/56094749/75817834-d384d780-5d65-11ea-9376-e496609c9ae8.png)
![Captura de pantalla (4195)](https://user-images.githubusercontent.com/56094749/75817837-d7185e80-5d65-11ea-8aa0-a59bc47e7cc4.png)

**Comment by michael200013** [comment]
also reseting windows is not an option i have sooo much TB of data and games/programs/savegames/document. installed

**Comment by W4RH4WK** [comment]
See #231.

**Comment by michael200013** [comment]
thanks, finally works the sign in again just had to turn on the correct services again.
