### ISSUE TITLE
Xbox game bar is not working

### ISSUE THREAD

**Issue by syrevision** [W4RH4WK/Debloat-Windows-10#235]
I choose the "optimize-user-interface.ps1" and the "remove-default-apps.ps1" scripts, and now the xbox game bar is not working, on the settings app when I click on Games, then "Game Bar", then when I put the switch on, go back and enter again, the switch is off, what I can do to revert the setting? please, I need help

**Comment by engunneer** [comment]
look at what is happening in scripts/optimize-user-interface.ps1 around line 30. it's making a registry key to disable the game bar. if you remove (or rename to be same) the registry key, it might fix your problem.

**Comment by syrevision** [comment]
You're a master, It get fixed!!!
