### ISSUE TITLE
Alvr issue

### ISSUE THREAD

**Issue by gamingtheohd** [W4RH4WK/Debloat-Windows-10#236]
So i have tried this scripts and after i restarted my pc i wanted to play vr with ALVR on my quest but now my headset dosent apear.So basicly my issue has something to do with wifi/fierwall.If someone can help me thanks

**Comment by gamingtheohd** [comment]
oh yea and i dont know why my resotore point isn't there anymore.So if i can recover the restore point or just wait for a major windows update to help me.

**Comment by W4RH4WK** [comment]
Assuming it has to do with firewall / block list, there is a dedicated firewall rule that blocks some IPs, disable that one. And rename `C:\WINDOWS\System32\drivers\etc\hosts` to something else, this is the file that blocks certain domains.

If this does not help, go through the list of services that get disabled, and re-enable them.

**Comment by gamingtheohd** [comment]
ok i will try now

**Comment by gamingtheohd** [comment]
Nope not working i have tryed to rename and turend off windows defender and fierwall and not working

**Comment by W4RH4WK** [comment]
Okay, than this issue is unlikely to be network related. Can you try re-enabling all services that have been disabled.

**Comment by gamingtheohd** [comment]
Already tryed

**Comment by gamingtheohd** [comment]
Not woroking right now I try to get to an earlier version of Windows so it will restore all the settings and apps

**Comment by gamingtheohd** [comment]
Nope not working. What can I do

**Comment by W4RH4WK** [comment]
If it's not related to network or disabled services, I am running out of ideas. My last guess is that the software you are running depends on one of Microsoft's Apps that get removed by the scripts.

I don't know whether they can be reinstalled properly. My suggestion would be to reinstall the system.

**Comment by gamingtheohd** [comment]
I tried to reinstall windows butt keep files not working

**Comment by W4RH4WK** [comment]
If you did a reinstall and only kept your personal files, no system specific files, then your issues does not originate from these scripts. None of the things these scripts touch persist across reinstalls.
