### ISSUE TITLE
Re-enable Windows Defender?

### ISSUE THREAD

**Issue by chrisvtheactivist** [W4RH4WK/Debloat-Windows-10#240]
Hey I did the script and it worked, however I realized that I actually wanted windows defender. Is there a way to get it back?

**Comment by W4RH4WK** [comment]
Have a look at `disable-windows-defender.ps1`. It disables scheduled tasks and services and adds some group policy entries.

First clear the group policy entries, then re-enable the services, then re-enable the scheduled tasks. Restart and you should be good to go.

**Comment by chrisvtheactivist** [comment]
Sorry I am not well versed in this kind of stuff. So to be clear, delete the section starting with "Disabling Windows Defender via Group Policies" and then change every "AutorunsDisabled" to "AutorunsEnabled" in the "Disabling Windows Defender Services?"

**Comment by W4RH4WK** [comment]
No, to it manually, not via the script:

Open the group policy editor, navigate to Windows Components and go through each Windows Defender folder, resetting all entries. Should only be a handful. You notice them as the state says something different than *Not configured*.

![image](https://user-images.githubusercontent.com/328798/80926537-3ca1bf00-8d98-11ea-8962-86d5b0409624.png)

In the services control panel, re-enable the services with *Windows Defender* in their name.

![image](https://user-images.githubusercontent.com/328798/80926587-6529b900-8d98-11ea-8b60-98d647ce59fe.png)

In the scheduled tasks control panel, re-enable the corresponding scheduled tasks. Found in Microsoft > Windows > Windows Defender.

![image](https://user-images.githubusercontent.com/328798/80926617-96a28480-8d98-11ea-9a3d-f667dbe6338d.png)

**Comment by chrisvtheactivist** [comment]
Thank you!

**Comment by OldWorldOrdr** [comment]
The group policy editor is only available in windows 10 pro, most users who get windows with their computer (like me) have windows 10 home.  Please provide instructions for reverting the change without the group policy editor or just provide a script to re enable windows defender.

**Comment by W4RH4WK** [comment]
Windows 10 Home is not supported by this project. You can find some guides online on where the corresponding registry keys are located.
