### ISSUE TITLE
How can i get Microsoft Store back to work?

### ISSUE THREAD

**Issue by Gastongaudio** [W4RH4WK/Debloat-Windows-10#241]
Hi everybody,
 after running the scripts of course M.S. refused to work properly. I now need it for apps I can't get otherwise. Is there any way to get it back to work?
-Basically, every time I try to install n app I get this message: AN ERROR OCCURRED

**Comment by W4RH4WK** [comment]
There could be a bunch of reasons as the Windows Store relies on a few services that get disabled by these scripts, assuming you are running them in their default configuration. I don't know about all dependencies by heart, but the most notable one is Windows Defender. See #240 on how to re-enable Windows Defender.
