### ISSUE TITLE
Search still shows removed apps

### ISSUE THREAD

**Issue by Daksh777** [W4RH4WK/Debloat-Windows-10#242]
So for example the camera app is removed but if you search it, it's still there. Any solution to remove all these removed apps from the search results?

**Comment by W4RH4WK** [comment]
Are you using the regular start menu for searching?

**Comment by GameSpeck** [comment]
> Are you using the regular start menu for searching?

I did not modify the start menu at all so yes

**Comment by W4RH4WK** [comment]
I am not using the default start menu as it had various issues with search for me. Googling led me to this: https://www.tenforums.com/software-apps/87957-remove-uninstalled-apps-show-up-windows-search.html

Have you had a look at this?

**Comment by GameSpeck** [comment]
I tried that but none of them seem to work, apps are still present

**Comment by W4RH4WK** [comment]
I am afraid I can't help here. I ditched the original start menu because of issues like that.

I'll keep the issue open with the 'help-wanted' label. Maybe something comes up in the future.

**Comment by mIcHyAmRaNe** [comment]
hello, i'm not having this problem so i can't test my idea. 
my theory is:
i think that the windows search cache the installed apps to make finding it more fast.
so when we uninstall an app, the cache is not rebuild so search engine still show the app. 

so i searched about that and i found something that you could test: (follow the second point: "Delete the Windows Search Index File")
https://www.techwalla.com/articles/how-to-delete-a-windows-search-index

**Comment by Daksh777** [comment]
I was unable to delete the index file due to some permission problems but yesterday I had clean installed Windows 1909 and when I used the debloater, it worked just fine. I assume this was some problem with the Windows OS itself. I will close this ticket for now because I have no such issues on the clean installed version.
