### ISSUE TITLE
Retain Black Command Prompt Title Bar

### ISSUE THREAD

**Issue by svpaz7** [W4RH4WK/Debloat-Windows-10#243]
I noticed that running these scripts will cause my command prompt title bar to become white.
How do I revert it and keep it black?

**Comment by W4RH4WK** [comment]
Does enabling *Title bars and window borders* in the *Colors* settings page work?

![image](https://user-images.githubusercontent.com/328798/82158222-c5375980-9886-11ea-8628-7ab28756bcde.png)

**Comment by svpaz7** [comment]
> Does enabling _Title bars and window borders_ in the _Colors_ settings page work?
> 
> ![image](https://user-images.githubusercontent.com/328798/82158222-c5375980-9886-11ea-8628-7ab28756bcde.png)

Hi, I just tried running the scripts again after a fresh windows update. It seems like the script doesn't change the cmd title bar at all - it remains black.
My mistake, I should've checked if this is still the issue before posting this.
