### ISSUE TITLE
disable-windows-defender.ps1 not working properly but ...

### ISSUE THREAD

**Issue by chneau** [W4RH4WK/Debloat-Windows-10#244]
Hello,

`disable-windows-defender.ps1` didn't work for me on this version of windows:
- Windows 10 Pro Insider Preview 19577.1

I'm not a specialist of all this windows power shell commands, but I have found on this website https://theitbros.com/managing-windows-defender-using-powershell/ this command:

```powershell
New-ItemProperty -Path “HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender” -Name DisableAntiSpyware -Value 1 -PropertyType DWORD -Force
```

After a reboot it just works:
- no more windows defender processes
- all (WdBoot, WdFilter, WdNisDrv, WdNisSvc, WinDefend) windows defender services Stopped

**Comment by gxgl** [comment]
Yes! The thing that should be done before running the script is to go to the security settings and disable the Tamper protection.


It will work after that. 




Trimis din Outlook Mobile







On Mon, May 18, 2020 at 1:08 PM +0300, "Charles Neau" <notifications@github.com> wrote:
















Hello,



disable-windows-defender.ps1 didn't work for me on this version of windows:



Windows 10 Pro Insider Preview 19577.1





I'm not a specialist of all this windows power shell commands, but I have found on this website https://theitbros.com/managing-windows-defender-using-powershell/ this command:

New-ItemProperty -Path “HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender” -Name DisableAntiSpyware -Value 1 -PropertyType DWORD -Force



After a reboot it just works:



no more windows defender processes

all (WdBoot, WdFilter, WdNisDrv, WdNisSvc, WinDefend) windows defender services Stopped

**Comment by chneau** [comment]
Ohhhh... alright I might have forgot to do that...

Thank you :-)
