### ISSUE TITLE
Couldn't disable wscsvc and Windows Defender Services

### ISSUE THREAD

**Issue by R4vz** [W4RH4WK/Debloat-Windows-10#247]
I could execute all the scripts successfully, but couldn't disable only wscsvc and Windows Defender Services from disable-services.ps1 and disable-windows-defender.ps1 respectively throwing an error "Permission Denied".
Also tried editing them manually into registry kept getting error "Cannot create value: Error writing to the registry". Had to create a .reg file manually with the registry values and execute it and idk how it worked. BTW I'm running the latest Win10 v2004.

**Comment by W4RH4WK** [comment]
Disabling Windows Defender has been a pain in the ass for some time now. If you really want to disable the services (and scheduled tasks) download the sysinternals suit, reboot into safe-mode and use `Autoruns64.exe` to disable services (and scheduled tasks). Note that system services might be hidden on default:

![image](https://user-images.githubusercontent.com/328798/83529582-d4571200-a4ea-11ea-8957-3b47647597db.png)

**Comment by R4vz** [comment]
I searched for "defender" tag in Autoruns and found few entries, does unchecking those entries under Autorun Entry disable them or should I delete the entry? And then run the "disable-services.ps1" and "disable-windows-defender.ps1" script later?

**Comment by R4vz** [comment]
Well I did uncheck all the entries when searched for "defender" tag in Autoruns64 and boot into windows. Ran disable-services.ps1 script, and the following error came up.
Set-Service : Service 'Security Center (wscsvc)' cannot be configured due to the following error: Access is denied
At C:\Debloat\scripts\disable-services.ps1:31 char:34
+     Get-Service -Name $service | Set-Service -StartupType Disabled
+                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (System.ServiceProcess.ServiceController:ServiceController) [Set-Servi
   ce], ServiceCommandException
    + FullyQualifiedErrorId : CouldNotSetService,Microsoft.PowerShell.Commands.SetServiceCommand


While I ran disable-windows-defender.ps1 script and this time there were no errors.

**Comment by W4RH4WK** [comment]
If you unchecked them, it should already be disabled, no need to run the script.

**Comment by R4vz** [comment]
Thank you sir for your response, much appreciated. This is a great project and keep up the good work.
