### ISSUE TITLE
Install OneDrive

### ISSUE THREAD

**Issue by jorzuniga** [W4RH4WK/Debloat-Windows-10#251]
How can I delete this policies Disable OneDrive via Group Policies

force-mkdir "HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\OneDrive"
Set-ItemProperty "HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\OneDrive" "DisableFileSyncNGSC" 1

When I make this to change to 0 value, the system dont save the data and if I reboot the value change to 1 again

**Comment by W4RH4WK** [comment]
Should be this one:

![image](https://user-images.githubusercontent.com/328798/84386236-41f0f580-abf1-11ea-8780-72d69bc19674.png)

**Comment by Luffitys** [comment]
Issue should be marked as closed, since there's no further report/input
