### ISSUE TITLE
I want to prevent the .ps1 scripts from removing certain apps

### ISSUE THREAD

**Issue by svpaz7** [W4RH4WK/Debloat-Windows-10#252]
Hi, I noticed that the .ps1 scripts remove the Camera and the Snip and Sketch applications.
I run these scripts constantly to ensure that bloatware is removed after windows updates, so it'd be really convenient that I know how to prevent the scripts from removing certain apps so I won't have to keep on downloading them again.

**Comment by W4RH4WK** [comment]
Just put a `#` before the corresponding line in the `remove-default-apps.ps1` script. There are already a few lines present in the script that have a `#` at the start.

**Comment by svpaz7** [comment]
> Just put a `#` before the corresponding line in the `remove-default-apps.ps1` script. There are already a few lines present in the script that have a `#` at the start.

Thanks. I can't seem to find which line is for "Snip & Sketch. Is it the "Microsoft.ScreenSketch" one?

**Comment by W4RH4WK** [comment]
Yes, you can just google the identifier (`Microsoft.ScreenSketch`) and it will take you to the Windows Store page, as most of them come from the Windows Store.

https://www.microsoft.com/en-us/p/snip-sketch/9mz95kl8mr0l?activetab=pivot:overviewtab
