### ISSUE TITLE
Ease of Access

### ISSUE THREAD

**Issue by elixalton** [W4RH4WK/Debloat-Windows-10#255]
I want to completely unistall and disable ease of acsess apps like **narrator, magnifier, speech recognition, steps recorder**.
these are just useless and unwanted applications using space.....

**Comment by W4RH4WK** [comment]
I do not plan to remove any of those. The ones you mentioned have been around for ages and I don't think they waste a significant amount of space (feel free to correct me with concrete numbers). Compared to other apps, they are far less intrusive and are commonly considered part of an operating system (see equivalents in macOS and Linux desktop environments).

However, I can point you in a direction that may help you removing these parts in a cleaner fashion. [nLite](https://www.nliteos.com/) is deployment tool that allows you to customize a Windows ISO prior installation. I've used it back in the days of Windows XP and Windows 7. It provides a lot of options, removing accessibility tools is one of them IIRC.
