### ISSUE TITLE
Keyboard layout changed in applications

### ISSUE THREAD

**Issue by ngoldack** [W4RH4WK/Debloat-Windows-10#264]
Hi everyone,

everything works fine, but when I use any programm (Windows Explorer, Terminal, Chrome, Firefox, VSCode, Notepad++, etc.) my keymap is changed from my normal systemwide DE-DE to EN-US. But when I type in the windows search bar in the bottom left it behaves normal.

Any suggestions?

**Comment by gxgl** [comment]
Hello Nicolas, 




Did you try the old fashion way, the SHIFT+Alt, key combination? 




Open up VSCode, click into a document and try the combo. 


Also look in the tray to see the change from EN to DE. 




Regards, 


George 




Obțineți Outlook pentru Android







On Sun, Aug 16, 2020 at 11:21 PM +0300, "Nicolas Goldack" <notifications@github.com> wrote:















Hi everyone,


everything works fine, but when I use any programm (Windows Explorer, Terminal, Chrome, Firefox, VSCode, Notepad++, etc.) my keymap is changed from my normal systemwide DE-DE to EN-US. But when I type in the windows search bar in the bottom left it behaves normal.


Any suggestions?

**Comment by Raiv3n** [comment]
![grafik](https://user-images.githubusercontent.com/1354182/90372802-431b2480-e071-11ea-8b6a-bf9f7ed02831.png)

Didn't helped either. As you can see in the image, under language settings in windows there is not even an option for english.

**Comment by gxgl** [comment]
Allright,

 

Let’s check…

Click on Deutsch (Deutschland) then click on Options (maybe Optzionen or so in DE) and see under Keyboards if you have something extra than DE.

 

George

**Comment by gxgl** [comment]
Sorry... If there is something extra, remove it.

**Comment by W4RH4WK** [comment]
I'm not sure whether this is related to the scripts. We don't intentionally change any of the language related settings, although, the scripts are only supported on an English installation.

I use Windows + Space to switch keylouts exclusively and it changes the layout for the whole system, not just window or application based.

For what it's worth, here is my keyboard setup:

![image](https://user-images.githubusercontent.com/328798/90378506-bcb71080-e079-11ea-8975-ed0a3552de99.png)

![image](https://user-images.githubusercontent.com/328798/90378541-c3de1e80-e079-11ea-9e63-0580fda15202.png)

![image](https://user-images.githubusercontent.com/328798/90378568-d35d6780-e079-11ea-9df9-b4750e1bc5e8.png)

![image](https://user-images.githubusercontent.com/328798/90378589-d9ebdf00-e079-11ea-8e54-e7d524168102.png)

![image](https://user-images.githubusercontent.com/328798/90378625-e112ed00-e079-11ea-9d42-052ea03cac8b.png)

**Comment by ngoldack** [comment]
All of those changes didn't helped. I did a reinstall which solved the issue but thanks anyway!
