### ISSUE TITLE
Restore The New Windows 10 Volume Slider

### ISSUE THREAD

**Issue by iiMahfoudh** [W4RH4WK/Debloat-Windows-10#271]
When I Do All Scripts I Just Realise That Volume Slider Back To Windows 7 Style So Plz Help Me To Get My Windows 10 Volume Slider Back

**Comment by W4RH4WK** [comment]
Remove `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\MTCUVC`. See corresponding line in `optimize-user-interface.ps1`. Please do not run these scripts blindly, as stated in the README.

**Comment by iiMahfoudh** [comment]
Thanks Man <3
