### ISSUE TITLE
No internet 

### ISSUE THREAD

**Issue by sappy0** [W4RH4WK/Debloat-Windows-10#272]
Well I encountered this problem today I first thought my router was being janky so I reset but that didn’t do squat so then I’ve tried every YouTube tutorial on “no internet, secured” and none of that seemed to fix the problem and then I checked out other reports of “no internet/no sound” nothing has seemed to work and this only started happening after I downloaded debloat so I’m not 100% sure if it has to do with your program but it might. I’ve reserved everything from IP to all config to even deleting useless temp files... I don’t really know what I’m doing I’m probably going to wipe the computer and not debloat it but that’s just because computer only half works without internet. I do really like your program but it’s my fault for downloading on windows home anyway.

**Comment by W4RH4WK** [comment]
Hey thanks for opening an issue about this. Just recently we had a similar issue reported by someone else. It seems kinda hard to reproduce. Is your issue similar to #270?

**Comment by W4RH4WK** [comment]
I close this in favor of #270.
