### ISSUE TITLE
Does it works on brazillian language? Windows 10 Pro 2004

### ISSUE THREAD

**Issue by snuckdev** [W4RH4WK/Debloat-Windows-10#274]
Does it works on brazillian language? Windows 10 Pro 2004

**Comment by W4RH4WK** [comment]
I don't know. I am only using English. I suspect most changes are language independent. The only thing that comes to mind is the [start menu unpinning logic](https://github.com/W4RH4WK/Debloat-Windows-10/pull/115) which hasn't been merged.

As always, use a freshly installed system and thoroughly test it after running the scripts to ensure nothing relevant got broken.
