### ISSUE TITLE
Hope to optimize and delete the latest EDGE browser script

### ISSUE THREAD

**Issue by ilikeyi** [W4RH4WK/Debloat-Windows-10#275]
It always feels a bit imperfect, and the deletion is not clean. I hope the author will optimize it together.

https://github.com/ilikeyi/PowerShell-Uninstall-Edge/blob/main/latest.uninstall.edge.ps1

**Comment by ilikeyi** [comment]
The current problem is that the DEVTOOLS is not cleanly deleted and other additional remaining problems.

**Comment by W4RH4WK** [comment]
I am actually against uninstalling Edge even though most users of these scripts prefer other browsers. While the way Microsoft pushes Edge is way too intrusive, I suspect it is tightly integrated into the operating system. Or at least, will be in the future.

Thinking back, removing Internet Explorer caused various things to break in strange ways. I seem to recall that it even broke Windows Updates at one point. If you are planning to remove Edge and give that a test run, I suggest utilizing `dism.exe` as done in [experimental_unfuckery.ps1](https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/experimental_unfuckery.ps1).
