### ISSUE TITLE
Failed to remove hosts file

### ISSUE THREAD

**Issue by mikelty** [W4RH4WK/Debloat-Windows-10#278]
Hi I'm on windows 10 2004 19041.685 and ran your app as admin. I got the following console output;
`14:40:18 ERROR: Hosts: Failed to modify hosts file
Traceback (most recent call last):
  File "dwt_util.py", line 312, in host_file
IOError: [Errno 22] invalid mode ('a') or filename: 'C:\\Windows\\System32/drivers/etc/hosts'`
Help plz.

**Comment by W4RH4WK** [comment]
`File "dwt_util.py", line 312, in host_file IOError`

I think you are on the wrong project. There is no `dwt_util.py` here. I suspect this is what you are looking for:
https://github.com/10se1ucgo/DisableWinTracking
