### ISSUE TITLE
Using "disable-services" stops Sign-In Options in settings from working.

### ISSUE THREAD

**Issue by LiamGale** [W4RH4WK/Debloat-Windows-10#279]
I have narrowed it down to the "disable-services" script causing the problem. When running the scripts and restarting to make sure everything is still working, when I go into Settings -> Accounts and when I click "Sign-in options" it just doesnt do anything. On some machines when clicked, freezes settings and then crashes, others just freezes on the click animaiton and stays until settings is restarted. The machines im trying to apply this to are running Windows 10 20H2 (Home and Pro).

I fixed the issue by reversing the "disable-services" script to re-enable the services.
To re-enable the services I changed line 31 "Get-Service -Name $service | Set-Service -StartupType Disabled" to:
"Set-Service $service -StartupType Automatic".

I havent had the time to narrow it down to what service is causing the problem but I hope you can give me some input on what might be causing the issue.

**Comment by LiamGale** [comment]
Here is a video of the problem. Also when you close settings after it freezes it breaks the settings button in start for a few seconds (also happens with Windows + i).

https://user-images.githubusercontent.com/47081685/104136480-5adfa600-538e-11eb-9f8c-5398fe7c369b.mp4

**Comment by W4RH4WK** [comment]
The *sign-in options* dialogue contains features like *Windows Hello Face* and *Windows Hello Fingerprint* which are both biometric authentication services. I therefore suspect the main culprit being the *WbioSrvc* service, as according to the name, it is related to biometrics.

I strongly advice against using biometrics for any kind of authentication, despite being more convenient.

**Comment by LiamGale** [comment]
That seems to have fixed it. I agree with you that using windows biometrics is not a good idea. But setting Windows Biometrics Service to "Automatic" fixed the problem, even if the service is not started the sign-in options now works just fine. I guess the biometrics stuff wont work tho, but im not going to use anyway.
