### ISSUE TITLE
audio menu gone

### ISSUE THREAD

**Issue by mountaser** [W4RH4WK/Debloat-Windows-10#281]
![image](https://user-images.githubusercontent.com/17933154/107861153-a99eb680-6df8-11eb-94ce-3aad56fe412b.png)
am on 1909 build 18363.1316 and after applying the scripts i started getting this instead of the normal modern menu when i press on the audio icon any idea why or how to fix it ? this happened on a fresh win 10 install

**Comment by W4RH4WK** [comment]
Remove `HKLM:\Software\Microsoft\Windows NT\CurrentVersion\MTCUVC`.
