### ISSUE TITLE
re-enable game bar?

### ISSUE THREAD

**Issue by thaynos** [W4RH4WK/Debloat-Windows-10#294]
how do i re-enable game bar? i tried to do it from settings but it keeps switching back to off when i exit the game bar window

**Comment by thaynos** [comment]
absolutely nothing happened. also the xbox ap and game bar app was uninstalled and i had to reinstall it. but even after doing the cmmand and restarting i still cant capture using it and the shortcuts dont work...

**Comment by W4RH4WK** [comment]
There are also some Xbox related services that get disabled, try to re-enable them. If that doesn't help I have no idea whether this feature can be restored.

For what it's worth, I've been recording gameplay using [OBS](https://obsproject.com/). It's not as straight forward, but gives you a lot more options.

**Comment by thaynos** [comment]
im not sure which services you mean? i saw another guide and i re enabled 3-5 services. i use game bar for clipping and organization.

**Comment by W4RH4WK** [comment]
These services:

"XblAuthManager"
"XblGameSave"   
"XboxNetApiSvc"

**Comment by thaynos** [comment]
i fixed the issue by following the registry steps shown in this guide
Enable or Disable Game DVR or Game Bar in Windows 10 (thewindowsclub.com)
<https://www.thewindowsclub.com/enable-disable-game-dvr-windows-10>
also can you add how to re-enable features in documentation?

**Comment by W4RH4WK** [comment]
Re-enabling things is not supported in general. These scripts are intended for automatic deployment. If your chosen modifications cause issues, change them and redeploy. At least that's the intention. There are other, more interactive tools available that are target at non-sysadmins. These tools commonly offer undo functionality.
