### ISSUE TITLE
optimize-windows-update.ps1 question

### ISSUE THREAD

**Issue by porssimies** [W4RH4WK/Debloat-Windows-10#295]
The descriptions says _"This script optimizes Windows updates by **disabling** automatic download"_ but why the "NoAutoUpdate" registry property is set to 0 instead of 1 ?

`Set-ItemProperty -Path "HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\WindowsUpdate\AU" "NoAutoUpdate" 0`

**Comment by W4RH4WK** [comment]
Good catch. Thank you.
