### ISSUE TITLE
Where to save PSM1 files 

### ISSUE THREAD

**Issue by Melaku2024** [W4RH4WK/Debloat-Windows-10#318]
Where am I to save the 2 psm1 files on c drive 
New-FolderForced.psm1
take-own.psm1

Getting the below error 
Import-Module : The specified module '\..\lib\take-own.psm1' was not loaded because no valid module file was found in any module directory.

It would be wonderful if you could provide me on how to use those two files to run remove-default-apps.ps1 

Import-Module -DisableNameChecking $PSScriptRoot\..\lib\take-own.psm1
Import-Module -DisableNameChecking $PSScriptRoot\..\lib\New-FolderForced.psm1
Thanks

**Comment by W4RH4WK** [comment]
Download the whole repository, extract everything, and run the scripts as described in the README. You don't have to make any changes to the directory layout, .psm1 files are included using relative paths.
