### ISSUE TITLE
how delete it?

### ISSUE THREAD

**Issue by adjajdsfj** [W4RH4WK/Debloat-Windows-10#320]
tell me please how turn off this code? i want to use defender, please tell me)

**Comment by JustMyGithub** [comment]
Just delete disable-windows-defender.ps1 before usage. If used already just look at this file and do the opposite (active the tasks which are disabled by the script, enable the services ...)

**Comment by adjajdsfj** [comment]
please explain me how to do it, i am not very good in it

**Comment by adjajdsfj** [comment]
how to look what tasks are blocked?

**Comment by adjajdsfj** [comment]
> Just delete disable-windows-defender.ps1 before usage. If used already just look at this file and do the opposite (active the tasks which are disabled by the script, enable the services ...)

tell me please

**Comment by heshtur** [comment]
Look at the pinned issue asking the same question you did, [here](https://github.com/W4RH4WK/Debloat-Windows-10/issues/240). Good luck.
