### ISSUE TITLE
Local Windows Search Unavailable

### ISSUE THREAD

**Issue by Marc05** [W4RH4WK/Debloat-Windows-10#35]
I'm not sure what caused it, but after running the scripts, the Windows Search toolbar in the taskbar did not work. I made sure to re-enable the service, but it did not make a difference. From what I could see referenced in the scripts, I only saw modifications to limit the search to local files and not removed completely (other than the service being disabled).

**Comment by W4RH4WK** [comment]
I'll fix this asap, I'll disable the search feature personally but it should not be disabled by default. As a sidenote I recommend using the Classic Shell startmenu which comes with its own search function.

**Comment by W4RH4WK** [comment]
As suspected this is a result of disabling the `searchUI.exe` process. I really wanted to disable that because *Cortana is listening*. But since it breaks a useful part of the OS this should not happen by default.

**Comment by Marc05** [comment]
I think it's also broken when removing the Cortana appx through DISM.

**Comment by W4RH4WK** [comment]
Yep, search breaks upon removing the Cortana related apps.
