### ISSUE TITLE
Restoring a few apps

### ISSUE THREAD

**Issue by jkaberg** [W4RH4WK/Debloat-Windows-10#38]
So I ran the remove apps ps script, all fine and well til I found myself in need of the store and calc :-)

So I tried restoring them but when I run the store or calc it tells me that I need to choose a program to run it with (none is installed so I can't choose any)

Any suggestions?

**Comment by W4RH4WK** [comment]
For the calculator: I really dislike the *new* calculator and would recommend using a different one. There is also a project which enables you to use the old calculator (Win7) in Win10, I believe.

For the store: In `remove-default-apps.ps1` the commands `Remove-AppxPackage` and `Remove-AppxProvisionedPackage` are used to remove the store. There is also a similar command for installing packages. You might be able to reinstall the store using these commands.

Lastly these apps are located inside `C:\windows\SystemApps` and `C:\Program Files\WindowsApps` (hidden folder) therefore copying the app folders from another computer over might work / help.

After all I don't think restoring already removed apps without deep understanding (which I do not have) of there internal package managing software (if you can even call that a package manager) may cause more harm than good. Hence you might be better of reinstalling the OS, I am sorry for the inconvenience, to me Microsoft should have provided a system-wide package manager like `apt-get` / `dpkg` before pushing that crappy Appstore. Now they will probably force the usage of their Appstore regarding certain applications / games so they can maximize the revenue created through ads and promotions. Something I'd really not want to see in a modern OS used by so many people day to day for their work. `</rant>`

**Comment by tumpio** [comment]
> There is also a project which enables you to use the old calculator (Win7) in Win10, I believe.
You can also install Microsoft calculator plus to get the "real" calc.exe :) (replace it or create a symlink)
http://www.microsoft.com/en-us/download/details.aspx?id=21622

**Comment by tumpio** [comment]
hmm maybe the store should not be removed by default, if it is not revertable. And maybe same with the force removing system apps.

For me it is not a problem, because I want to remove them all anyway!

**Comment by jkaberg** [comment]
yeah, I've poked at this for an hour now.. Store really seems like a problem to restore, but I'll have to go pro edition anyways so I'll keep it in mind. thans @W4RH4WK
