### ISSUE TITLE
Search gets disabled by default

### ISSUE THREAD

**Issue by W4RH4WK** [W4RH4WK/Debloat-Windows-10#39]
@joemg703 mentioned this in #5 and it occurred on [reddit](https://www.reddit.com/r/Windows10/comments/3n1eei/so_i_tried_to_debloat_windows_10_and_shits_not/) yesterday.

**Comment by boldsoon** [comment]
Going to explorer and making a search from there, it will pop a windows to speed search by activate indexing. This will make the search again.

**Comment by W4RH4WK** [comment]
Thanks for letting me know, as mentioned in the other topic, the Windows Search service gets deactivated, I have to change this. This should resolve the issue.
