### ISSUE TITLE
New script ideas

### ISSUE THREAD

**Issue by tumpio** [W4RH4WK/Debloat-Windows-10#4]
Some more ideas for new scripts:

- [x] ~~Enable title bar color~~ [1] This is officially in new preview build. [10]
- [x] Enable God Mode [2]
- [x] Disable new lock screen [3]
- [x] Disable new volume control [4]
- [x] Disable sticky keys [5]
- [x] Disable automatic device driver updates [6]
- [x] Enable legacy boot menu [7]
- [x] Remove quick access [8]
- [x] Disabling Live Tile Notifications in the Start Menu (script group could be "optimize-startmenu") [9]
- [x] Disable notifications center [11]
- [x] Disable unwanted scheduled tasks [12] [13] [14]

utils:
- [x] Run disk clean up tool with more options (cleanmgr /sageset:1 && cleanmgr /sagerun:1)
- [x] Boot to safe mode (bcdedit /set {current} safeboot minimal && shutdown /r /t 00) or Boot to Advanced start up options menu (shutdown /o /r /t 00)

[1]: http://www.windowscentral.com/replace-those-white-title-bars-windows-10-colors-theme
[2]: http://winsupersite.com/windows-10/enabling-godmode-windows-10
[3]: http://www.tenforums.com/tutorials/6567-lock-screen-enable-disable-windows-10-a.html
[4]: http://winaero.com/blog/enable-old-volume-control-in-windows-10/
[5]: http://blog.duklabs.com/?p=96
[6]: http://www.ghacks.net/2015/07/21/how-to-disable-driver-updates-from-windows-update/
[7]: http://www.eightforums.com/tutorials/5245-startup-options-enable-disable-windows-8-a.html
[8]: http://www.tenforums.com/tutorials/4844-quick-access-navigation-pane-add-remove-windows-10-a.html
[9]: http://www.askvg.com/how-to-disable-live-tiles-feature-for-all-apps-in-windows-8-and-later/
[10]: https://blogs.windows.com/bloggingwindows/2015/08/18/announcing-windows-10-insider-preview-build-10525/
[11]: http://winaero.com/blog/how-to-disable-notifications-in-windows-10/
[12]: http://www.hwinfo.com/misc/RemoveW10Bloat.htm
[13]: http://pastebin.com/8acsQB1x
[14]: http://akq.fi/w10/Win_10_tweakkeja_osa_3.txt

**Comment by KidSunday** [comment]
Wasn't sure if you had already implemented this idea - 
But, might I suggest disabling Live Tile Notifications in the Start Menu
http://www.askvg.com/how-to-disable-live-tiles-feature-for-all-apps-in-windows-8-and-later/

**Comment by W4RH4WK** [comment]
Big thanks, they all seem reasonable. I'll probably add them later on, depends a little bit on #5.

**Comment by W4RH4WK** [comment]
do you have any preference on which scheduled tasks should be disabled?

**Comment by tumpio** [comment]
Well, these scripts have something:
http://www.hwinfo.com/misc/RemoveW10Bloat.htm
http://pastebin.com/8acsQB1x
http://akq.fi/w10/Win_10_tweakkeja_osa_3.txt

**Comment by W4RH4WK** [comment]
Looks like a lot to cover `Oo`. I'll go over it when I have more time. Thanks for the input let me know if you find a certain feature of these scripts which is missing here.

**Comment by tumpio** [comment]
The first script has more registry changes for telemetry disabling:
```
@rem *** Remove Telemetry & Data Collection ***
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Device Metadata" /v PreventDeviceMetadataFromNetwork /t REG_DWORD /d 1 /f
reg add "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" /v "AllowTelemetry" /t REG_DWORD /d 0 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\MRT" /v DontOfferThroughWUAU /t REG_DWORD /d 1 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\SQMClient\Windows" /v "CEIPEnable" /t REG_DWORD /d 0 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat" /v "AITEnable" /t REG_DWORD /d 0 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\AppCompat" /v "DisableUAR" /t REG_DWORD /d 1 /f
reg add "HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection" /v "AllowTelemetry" /t REG_DWORD /d 0 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\WMI\AutoLogger\AutoLogger-Diagtrack-Listener" /v "Start" /t REG_DWORD /d 0 /f
reg add "HKLM\SYSTEM\CurrentControlSet\Control\WMI\AutoLogger\SQMLogger" /v "Start" /t REG_DWORD /d 0 /f
```

**Comment by W4RH4WK** [comment]
neat, gotta add them later

**Comment by tumpio** [comment]
Second script also disables Defender services:

```
sc config WinDefend start= disabled > NUL 2>&1
sc config WdNisSvc start= disabled > NUL 2>&1
```

**Comment by tumpio** [comment]
The third script also disables a lot of system startup entries, disables logging and does many other changes. That script will definitively brake something..

**Comment by W4RH4WK** [comment]
disabling windows defender service did not work for more ever in Win10, group policy is the only way to disable windows defender AFAIK.

**Comment by m-dwyer** [comment]
I've successfully removed Windows Defender.. I'm grabbing a list of any keys containing *Windows-Defender* in HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\Packages, then after granting myself write access I remove the Owner subkey and remove the package with DISM.

You may or may not want to completely remove packages though, and it may or may not break things.

**Comment by tumpio** [comment]
@m-dwyer Do you get e.g. the definition updates after doing this? Updates to Windows Defender could fail, or maybe they detect if the package exists, but probably not.

**Comment by W4RH4WK** [comment]
`HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based` looks very interesting. It seems like you can remove (and break) lots of stuff. I like it ^^.

I'll remove Windows Defender using this method and see what happens.

**Comment by W4RH4WK** [comment]
I'll add it to the list buy disabled by default. It seems like Windows Defender gets removed from the system but the corresponding bullet is still present in the settings menu (`Settings > Update & Security`). Upon selecting the entry the settings menu crashes.
