### ISSUE TITLE
Describe how to Run as Admin on ReadMe

### ISSUE THREAD

**Issue by Reyncor** [W4RH4WK/Debloat-Windows-10#42]
That would sure be helpful in the read me... I'm not familiar with Powershell... only use windows for games and the 10 tons of hidden bloat is disturbing. I'm sure I'll figure it out, but it's something that should really be on the ReadMe.

Thank you!

EDIT: Turns out it's quite involved to run them all as administrator... I trust your sensible defaults and really don't care much about... fire away. It would be nice to have a run all button/command.
http://superuser.com/questions/108207/how-to-run-a-powershell-script-as-administrator

EDIT #2: Wow, Tip http://superuser.com/a/108405 works fantastically, all your scripts should have it... with an include of course.

**Comment by tumpio** [comment]
You can try my run helper script too
https://github.com/W4RH4WK/Debloat-Windows-10/pull/1

**Comment by W4RH4WK** [comment]
No offense @Reyncor, but if you are not familiar with Powershell and would rely on my defaults, this is probably not for you. You may have a better experience using [DisableWinTracking](https://github.com/10se1ucgo/DisableWinTracking).

**Comment by Reyncor** [comment]
@W4RH4WK alright then. I'm just desperately looking for an easy way remove all the bloatware preinstalled on Windows 10. Disable WinTracking is more focused on privacy and leaves a lot behind... such as the OneDrive file explorer shortcut, Windows 8 style apps,  the Windows Store, Windows Defender, bing, cortana etc.

**Comment by W4RH4WK** [comment]
Sounds like a good idea for a fork. I already have dedicated scripts for OneDrive and Defender, it should be straight forward to build upon them. `remove-default-apps` uninstalls most of the app styles already. If you want to go even further take a look at `dism.exe`. At 27ae62d you will find some directives for `dism.exe` in the `remove-default-apps` script. But be aware that the removal of certain packages may break your system. (For example, removing all xbox related packages yields a boot loop.)

Also checkout [Classic Shell](http://www.classicshell.net/) for an improved start menu.

**Comment by W4RH4WK** [comment]
@Reyncor I just found a set of needles for `dism.exe` they might be useful to you. Here is the [gist](https://gist.github.com/W4RH4WK/882c6e0c4cdfca494ba2#file-dism-txt)
