### ISSUE TITLE
Unable to see Download Now button in the iTunes download page

### ISSUE THREAD

**Issue by overdrivemachines** [W4RH4WK/Debloat-Windows-10#43]
Go to http://www.apple.com/itunes/download/
The download button will not appear. The button's image is:
https://a248.e.akamai.net/7/248/51/20080903/swdlp.apple.com/iframes/IMAGES/itunes_download_now752014.png

The reason why it doesn't work is because a248.e.akamai.net is in the block-telemetry.ps1 file.

**Comment by W4RH4WK** [comment]
Since you opened an issue about this you requesting removing `a248.e.akamai.net` from the list?

**Comment by overdrivemachines** [comment]
Yes
