### ISSUE TITLE
Windows 10 updates nag screen

### ISSUE THREAD

**Issue by kykc** [W4RH4WK/Debloat-Windows-10#44]
After applying `optimize-windows-update.ps1` nag screen starts to appear if there's updates available: 
![screenshot](http://i.imgur.com/7zTuJBy.png)

The only solution that I've found is to restrict execution rights for `MusNotification.exe` and `MusNotificationUx.exe` to everyone (see [here](http://superuser.com/questions/972038/how-to-get-rid-of-updates-are-available-message-in-windows-10) and [there](https://www.reddit.com/r/Windows10/comments/3j8e2s/how_do_i_disable_this_fullscreen_update/))

FYI: It blocks mouse but doesn't block keyboard, so it can be killed from task manager without any problems :smile:

**Comment by kykc** [comment]
It can be down in PowerShell as follows:

```powershell
cd $Env:WinDir\System32
takeown /F .\MusNotification.exe
icacls .\MusNotification.exe /deny "Everyone:(X)"
takeown /F .\MusNotificationUx.exe
icacls .\MusNotificationUx.exe /deny "Everyone:(X)"
```

**Comment by W4RH4WK** [comment]
Nice, thanks for the input.
