### ISSUE TITLE
"turn on windows security center service" notifications

### ISSUE THREAD

**Issue by RayFoss** [W4RH4WK/Debloat-Windows-10#46]
I keep getting this warning after running a script that disabled it... Is there way to tell windows to shut up. I've already right clicked it and asked it to stop giving me notifications from this "app" but that doesn't work.

**Comment by W4RH4WK** [comment]
Hi Ray, did you already try this: <http://www.tenforums.com/antivirus-firewalls-system-security/11227-how-can-i-disable-turn-windows-security-center-service-warning.html>

**Comment by RayFoss** [comment]
The script takes over ActionCenter.dll, it's the nuclear option and might
have issues with updates. It does seem to have worked without issue.
Perhaps it should be part of the script that kills the action center
service.

**Comment by W4RH4WK** [comment]
While all of this still remains experimental, I dialed down on using nuclear methods. I am thinking about adding a script `experimental_unfuckery.ps1` which contains similar techniques and encourage people not to use it unless they really have / want to.

RIght now, *most* of the tweaks boil down to registry tweaks and removing packages via the intended path (PowerShell cmdlet).

**Comment by W4RH4WK** [comment]
As a side note, the Security Center Service does not seem to do anything for or against me. I have the service enabled on my one computer which runs windows.

**Comment by RayFoss** [comment]
Good point... Experimental fuckery sounds good. That would be specially
useful for power users who can have their system die at any point without
data loss.
