### ISSUE TITLE
disable-services.ps1 causes Security Center messages in the Action Center

### ISSUE THREAD

**Issue by HoDANG** [W4RH4WK/Debloat-Windows-10#47]
After running disable-services.ps1 there is a constant stream of error messages asking for the security center to be enabled :
![Windows Action Center](http://i.imgur.com/lwnixwC.png?1)
(I prefer the default action center because that is how I open up the ImmersiveSettings app to check for Windows Updates)

This is caused by : 
`"wscsvc"                                   # Windows Security Center Service`

I would not recommend taking this away, as I am sure many people would see it as an invasive service

However, I would suggest adding something to your script in order to prevent these messages from popping up constantly. 

I am searching how to remove these messages, and I will post back when/if I find a solution.

and thanks a bunch for the scripts  :smiley:

**Comment by W4RH4WK** [comment]
We just recently had a similar issue open #46, while it was resolved the solution seems a little too *invasive* to add it.

**Comment by HoDANG** [comment]
Ahh, sorry about that. Didn't even think to check the previous issues. My bad.

**Comment by W4RH4WK** [comment]
No problem, I'd like to have solution for this, but one that is more like a regkey or gp entry. Patching a DLL may yield problems somewhere down the line. Or may simply be overwritten again by an update.

**Comment by W4RH4WK** [comment]
Does this still happen to this extend after the anniversary update? One of my Windows desktops, which runs 24/7 only has one entry about the Security Center in the notification bar. And I only noticed a popup once in the last month.

**Comment by HoDANG** [comment]
I reinstalled windows a couple times, so I do not have this installed anymore. I also don't want to use the script and mess something up again. Sorry about that.

**Comment by W4RH4WK** [comment]
No problem, use whatever works for you mate.
