### ISSUE TITLE
Running Stock Script Causes Windows Store to Error

### ISSUE THREAD

**Issue by NikolaeVarius** [W4RH4WK/Debloat-Windows-10#48]
After running the block-telemetry script, the Windows Store seems to be unable to get a license file.

When attempting to update or install an app, the Store errors out with a generic 80072EFD code right when it attempts to ping the license server.

Don't think its the hosts file because when running the script without hosts entries, I still get the same error.

Continuing some tests

**Comment by W4RH4WK** [comment]
The block telemetry script also adds a firewall rule blocking certain IPs, can you try to disable the corresponding rule?

**Comment by NikolaeVarius** [comment]
Yep, confirming it works again when disabling the firewall rules. Need to figure out which one it is

**Comment by W4RH4WK** [comment]
@NikolaeVarius did you pin down which ip/domain caused issues?
