### ISSUE TITLE
disable-services.ps1 - services dependencies

### ISSUE THREAD

**Issue by obelix30** [W4RH4WK/Debloat-Windows-10#49]
disable-services.ps1 is disabling NetTcpPortSharing so it should also disable NetTcpActivator which depends on NetTcpPortSharing

**Comment by W4RH4WK** [comment]
Are you sure that's the name of the service? I cannot find it on my testing machine:

```
PS > Get-Service -name NetTcpActivator
Get-Service : Cannot find any service with service name 'NetTcpActivator'.
At line:1 char:1
+ Get-Service -name NetTcpActivator
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (NetTcpActivator:String) [Get-Service], ServiceCommandException
    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell.Commands.GetServiceCommand

PS > Get-Service -name NetTcpPortSharing

Status   Name               DisplayName
------   ----               -----------
Stopped  NetTcpPortSharing  Net.Tcp Port Sharing Service
```

**Comment by obelix30** [comment]
You are right I have checked this on machine with fresh Windows installation and such service is not there.   However I can find this service on my old laptop.  So it is installed together with some software later.   I will close the issue
