### ISSUE TITLE
Add restore/revert scripts

### ISSUE THREAD

**Issue by tumpio** [W4RH4WK/Debloat-Windows-10#5]
Should we add restore scripts?

**Comment by maci0** [comment]
Would a system restore point be sufficient ?

**Comment by W4RH4WK** [comment]
I am not certain system restore will undo all changes, especially since I do not know what future scripts will modify and whether these changes are covered by system restore. I'll think about adding an optional parameter `-Revert` to the scripts which will undo the script's effects.

**Comment by W4RH4WK** [comment]
ref #38

**Comment by joemg703** [comment]
How do I revert the changes? I dont know how and it broke my search button

**Comment by W4RH4WK** [comment]
I still haven't found a practical way to simple revert everything done by the scripts. Some people say system restore works for them. The interesting thing is that the search functionality should not be broken by default. Or at least it wasn't... maybe Microsoft changed some things in an update. A similar issue popped up yesterday on [reddit](https://www.reddit.com/r/Windows10/comments/3n1eei/so_i_tried_to_debloat_windows_10_and_shits_not/).

I'll have to look into this, maybe tweaking the defaults will be enough. But I'm sorry to tell you that there is no /simple/ revert to the scripts in general. I'll let you know if I find out what's causing the breakdown of the search button / functionality.

**Comment by W4RH4WK** [comment]
@joemg703 I just noticed something: I still disable the windows search service by default, maybe this is causing the problem. Can you try re-enabling the "Windows Search" service using the service management tool (usually located under administrative tools)

**Comment by W4RH4WK** [comment]
Adding restore / revert scripts will add a lot of complexity since some actions cannot simply be undone. I also added a notice to the README about this. Even if it would be possible to add revert functionality for every script now, I cannot guarantee that the revert scripts will work after future Windows updates have been installed.
