### ISSUE TITLE
Remove this with the script aswell Candy Crush Soda Saga 

### ISSUE THREAD

**Issue by bittin** [W4RH4WK/Debloat-Windows-10#50]
king.com.CandyCrushSaga
Candy Crush Soda Saga

have some more stuff too will get them to you later during the week

**Comment by Smartis2812** [comment]
Push! Most hated preinstalled App! 😒

**Comment by W4RH4WK** [comment]
`king.com.CandyCrushSaga` is already part of the list, but I just added it as wildcard which should also work fine.

**Comment by bittin** [comment]
king.com.CandyCrushSodaSaga is Soda Saga sorry wrote wrong in the first message 
emailed me coworker now to see if i can get the rest of his modifications and help you further

**Comment by bittin** [comment]
[script.zip](https://github.com/W4RH4WK/Debloat-Windows-10/files/335635/script.zip)
