### ISSUE TITLE
Block telemetry domains/IPs with a firewall

### ISSUE THREAD

**Issue by tumpio** [W4RH4WK/Debloat-Windows-10#6]
Should we use windows firewall to block the telemetry domains and IPs instead of using the hosts file?

see:
https://github.com/10se1ucgo/DisableWinTracking/issues/13

**Comment by maci0** [comment]
You can block hostnames through the hosts conf and IPs through a false route via 0.0.0.0
Some people will not use the windows FW but an external product. This will work for them as well.

**Comment by W4RH4WK** [comment]
@maci0 do you have any sources for this? I just tried it out inside a VM (using ping and web browser) it does not seem to work for me.

**Comment by yuureiu** [comment]
Windows hard codes certain IP and domain names related to updating and other Microsoft services into dnsapi.dll in the system32 folder. This is checked before the hosts file is checked, so any domains in this dll will override the corresponding host file entry if it exists.

This isn't new to Windows 10, and might go back as far as Windows XP.

I've seen a little discussion of this dll, as related to Windows 10, but most of it appears to be FUD. I have not seen anyone actually reverse engineer the dll.

**Comment by maci0** [comment]
@W4RH4WK https://github.com/10se1ucgo/DisableWinTracking/issues/7

**Comment by W4RH4WK** [comment]
In my testcase it did not even work to block arbitrary IP addresses using the hosts file. Maybe I am doing something wrong, but it does not seem to work. Any ideas how to advance? I don't really think Windows firewall is a good idea since some people will probably disable it, but if it blocks traffic to the IPs in question it's already better than the hosts file.

**Comment by W4RH4WK** [comment]
@maci0 thanks for the reference, I'll probably wait and see what @10se1ucgo comes up with use the same solution if applicable.

**Comment by tumpio** [comment]
@W4RH4WK the solution was to remove invalid entries:
https://github.com/10se1ucgo/DisableWinTracking/commit/591a492688b4ae76d6bf7ff0869b245dbd476674

**Comment by W4RH4WK** [comment]
@tumpio I saw that and will remove the invalid entries too. If I understood @yuureiu correctly we should still find a better way to block the hardcoded IP addresses.

**Comment by W4RH4WK** [comment]
closing this for now

**Comment by 10se1ucgo** [comment]
Forgot about this. @W4RH4WK, I've now implemented a way for blocking IP addresses. You can see the commit here: [1afd3e4](https://github.com/10se1ucgo/DisableWinTracking/commit/1afd3e4c30aad2b9580e239ba7d1d52ec4f09e37#diff-6e38f16215ae91c11fc5c54b74c66d54R272)

**Comment by W4RH4WK** [comment]
thanks for letting me know
