### ISSUE TITLE
enable-god-mode.ps1 does not respect changed Desktop folder location

### ISSUE THREAD

**Issue by dmbekker** [W4RH4WK/Debloat-Windows-10#62]
Background info: I've changed the Desktop folder location.  (it's on my D drive)

Issue: The shortcut created by `enable-god-modes.ps1` is still being put on the C: drive

Steps to reproduce
- Change your Desktop folder location.:
- 1. Right click C:\Users\<user>\Desktop
- 2. Click Properties
- 3. Click the "Location" tab
- 4. Select a folder and apply
- Run enable-god-mode.ps1

**Comment by dmbekker** [comment]
Possible solution. Use envoirment variables

```
PS D:\Users\David\Documents\GitHub\Debloat-Windows-10\utils> echo $env:UserProfile\Desktop\
C:\Users\David\Desktop\

PS D:\Users\David\Documents\GitHub\Debloat-Windows-10\utils> $DesktopPath = [Environment]::GetFolderPath("Desktop"); echo $DesktopPath
D:\Users\David\Desktop
```

I was unable to implement this into the script and fill a Pull Request, but my Powershell skills are close to none.

**Comment by W4RH4WK** [comment]
Here you go.
