### ISSUE TITLE
Errors after anniversary update

### ISSUE THREAD

**Issue by AscendantX** [W4RH4WK/Debloat-Windows-10#63]
I got a lot of errors when applying scripts immediately after clean install of win 10 x64 enterprise with anniversary update included (en_windows_10_enterprise_version_1607_updated_jul_2016_x64_dvd_9054264.iso)

The few that i can remember:
- line 73 in remove-default-apps.ps1 throws an error, so apps are not completely uninstalled
- defender uninstall throws some null object errors
- some registry entries don't exist

**Comment by W4RH4WK** [comment]
Thanks, I haven't found time to look into the anniversary update stuff.

**Comment by W4RH4WK** [comment]
Can you try with the latest version whether these issues still exist. And if so, copy paste the error messages please.

**Comment by AscendantX** [comment]
Tested again on the same version as stated above, installed in a VM, run scripts right after first boot.
Everything seems to be working fine, I received only 2 permission-access errors, but they may be related to my specific environment only.

For each attempt to edit "hosts" file in block-telemetry.ps1:
`Out-File : The process cannot access the file 'C:\Windows\System32\drivers\etc\hosts' because it is being used by
another process.
At C:\users\ghost\desktop\scripts\scripts\block-telemetry.ps1:155 char:34
+ ... echo "0.0.0.0 $domain" | Out-File -Encoding ASCII -Append $hosts_file
+                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], IOException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand
`

Once in fix-privacy-settings.ps1:
`Disable submission of Windows Defender findings (w/ elevated privileges)
sp : Attempted to perform an unauthorized operation.
At C:\users\ghost\desktop\scripts\scripts\fix-privacy-settings.ps1:92 char:1
+ sp "HKLM:\SOFTWARE\Microsoft\Windows Defender\Spynet" "SpyNetReportin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (SpyNetReporting:String) [Set-ItemProperty], UnauthorizedAccessExcepti
   on
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.SetItemPropertyCommand
`

Very good job on the fixes, thank you very much :-)

**Comment by AscendantX** [comment]
So i just found out that most of the entries in "hosts" file are present, only few of them threw an error, as if the script was adding another entry before finishing adding the previous one.

**Comment by W4RH4WK** [comment]
Need to double check whether all entries are present in the hosts file.

I encountered the same error regarding Windows Defender. I was not able to force permissions on that specific registry key to allow me to change it. I may just disable that line with a note attached.

Thanks for going through the effort of testing it again.

**Comment by replete** [comment]
I just wanted to feedback that a fresh install of Windows 10 Enterprise 64 1607 MSDN yielded no errors with the current version of scripts. All worked like a dream.

Thanks for your work on this.

**Comment by W4RH4WK** [comment]
Thanks for the feedback, I'll close this issue for now.
