### ISSUE TITLE
Does not update to anniversary update

### ISSUE THREAD

**Issue by ovidijusr** [W4RH4WK/Debloat-Windows-10#65]
When I try to update to anniversary update it restarts computer, after restart  it blinks and restarts back to old version without any changes. I think it may be because of debloat patch

**Comment by W4RH4WK** [comment]
Do you have any clues why the debloat scripts may have caused this. Did you run the part removing system components using `dism.exe` when you used the scripts. I mean stuff recently moved to `scripts/experimental_unfuckery.ps1`.

**Comment by W4RH4WK** [comment]
Will close this after 24h if nothing happens.
