### ISSUE TITLE
Can't access Bing.com after running "block-telemetry.ps1".

### ISSUE THREAD

**Issue by chella1cm** [W4RH4WK/Debloat-Windows-10#71]
I get "Your Internet access is blocked" error. I know i have to delete some lines from hosts file to get Bing back, but i don't know which ones.

Can you help me?

**Comment by leeoniya** [comment]
this happens to be Bing's ip: https://github.com/W4RH4WK/Debloat-Windows-10/blob/master/scripts/block-telemetry.ps1#L164

**Comment by chella1cm** [comment]
Wow, Thank you for your quick response. Fixed.
