### ISSUE TITLE
MarkC Mouse Acceleration Tweak Undo

### ISSUE THREAD

**Issue by maymays11** [W4RH4WK/Debloat-Windows-10#75]
Hello all,
The script that optimizes the user interface also applies the markc mouse acceleration tweak. I've applied it, and I don't like the new mouse sensitivity. How do I revert this change to the default sensitivity?
Thank you in advance

**Comment by W4RH4WK** [comment]
Here is the [official page](http://donewmouseaccel.blogspot.co.at/2010/03/markc-windows-7-mouse-acceleration-fix.html), the archive you can download over there contains a `.reg` file which resets sensitivity / acceleration back to its default value.

**Comment by maymays11** [comment]
Thank you!
