### ISSUE TITLE
Ever want to use Skype again?

### ISSUE THREAD

**Issue by molobox** [W4RH4WK/Debloat-Windows-10#79]
Hi,

After reinstalling Windows 10 Pro N x64 and using these great Debloat tools, I had trouble using Skype. Not the Entreprise version that comes with the OS, just the regular one.

Well I went to the "hosts" file in "C:\Windows\System32\drivers\etc" and removed the lines where "skype" appeared.

For the users of the Block-Telemetry script, I recommend quoting the lines as follows:

File: 
> Debloat-Windows-10/scripts/block-telemetry.ps1

Lines:
`   # "ui.skype.com",`
`   # "pricelist.skype.com"`
`   # "apps.skype.com"`

This will save you some trouble. 👍
Have a nice day!

Nicolas / Mole

**Comment by pepoweb** [comment]
I can second this issue. I have a few Win 10 Pro machines at work who have the same issue.
After the weekend I will try to find a way to reverse this.
Pepo

**Comment by pepoweb** [comment]
It seems skype also uses c.msn.com So if you have already ran the script you can edit C:\Windows\System32\drivers\etc\hosts and commend out the following lines:
...
# ”c.msn.com"
...
# "ui.skype.com"
# "pricelist.skype.com"
# "apps.skype.com"
...
Hope this helps.
Pepo

**Comment by molobox** [comment]
Thank you pepo, you're right, I had forgotten "c.msn.com"

**Comment by jkalousek** [comment]
In my case "s.gateway.messenger.live.com" also caused problems with skype.

**Comment by W4RH4WK** [comment]
Should I also comment the line containing "s.gateway.messenger.live.com"?

**Comment by majkinetor** [comment]
I have all those in my hosts file and my Skype works fine.

Skype 7.35.0.101 , my location Serbia/Belgrade.

**Comment by jkalousek** [comment]
(Disclaimer: I'm using this list in pfSense, so on my firewall - which however should not make a difference).
When I put "s.gateway.messenger.live.com" in blocked list, Skype on Windows 10 can't go online (it only shows rotating arrows).

Location: Czech Republic
Skype versions: 7.34.0103 (Windows 7) & 7.35.0.103 (Windows 10)

**Comment by majkinetor** [comment]
Must be location specific then ...

**Comment by majkinetor** [comment]
My list comes from https://github.com/StevenBlack/hosts

**Comment by jkalousek** [comment]
Btw can any of you actually reach "s.gateway.messenger.live.com" with tracert?

Because I get "Unable to resolve target system name s.gateway.messenger.live.com".

**Comment by majkinetor** [comment]
Looks like aforementioned github project had the same issue:
https://github.com/StevenBlack/hosts/issues/127

@jkalousek 
its reachable from http://www.monitis.com/traceroute

**Comment by jkalousek** [comment]
Ok, thanks for checking. So it would be good to put comment next to this host so people could find this faster.

**Comment by madeso** [comment]
login.live.com caused issues for me logging in to the latest skype classic (desktop version)

**Comment by pepoweb** [comment]
I can confirm that login.live.com is now also required to login to skype.
After taking that line out, it works again.
