### ISSUE TITLE
Permission Denied?

### ISSUE THREAD

**Issue by XThexOmenX** [W4RH4WK/Debloat-Windows-10#91]
After I set the executionpolicy to unrestricted I try "ls -Recurse *.ps1 | Unblock-File" and get this..

ls : Access to the path 'C:\Windows\system32\LogFiles\WMI\RtBackup' is denied.
At line:1 char:1
+ ls -Recurse *.ps1 | Unblock-File
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Windows\syst...es\WMI\RtBackup:String) [Get-ChildItem], U
   edAccessException
    + FullyQualifiedErrorId : DirUnauthorizedAccessError,Microsoft.PowerShell.Commands.GetChildItemCommand

I know running as admin doesn't grant access to system but is there something I'm doing wrong or a step I overlooked?

**Comment by XThexOmenX** [comment]
Looks like I can only get it to run when I activate the Admin account that has system access, I'm going to see if I can add more to this to enable the built in admin, use it's creds to run this on a normal 'user' account, the disable system again

**Comment by XThexOmenX** [comment]
![ps denied](https://cloud.githubusercontent.com/assets/24778492/21485583/734dec58-cb73-11e6-981b-e845617c8278.PNG)


uhh.. yes? thought that was already implied

**Comment by kn0rki** [comment]
you need to execute that in the script folder where you have downloaded the powershell files

**Comment by XThexOmenX** [comment]
I'm dumb, saw the "no user interaction" in the description and got giddy. 
called directory and it works. ignore my rookie mistake

**Comment by W4RH4WK** [comment]
No problem, glad you were able to resolve it :)
