### ISSUE TITLE
can't open local website

### ISSUE THREAD

**Issue by xyabcn** [W4RH4WK/Debloat-Windows-10#92]
after i use this remove-default-apps.ps1 and remove-onedrive.ps1, i can't open our local websites, like http://myweb , please help me check this, thank you.

**Comment by W4RH4WK** [comment]
Can you ping the host of the website?

**Comment by xyabcn** [comment]
couldn't find the host, but the windows7 computer can ping that websites

**Comment by W4RH4WK** [comment]
Please double check whether the target hostname (or similar) is inside `C:\WINDOWS\System32\drivers\etc\hosts`

**Comment by xyabcn** [comment]
there is nothing on hosts file, i just found if reinstall an app use the store like windows photos, then the computer can access the websites, i don't know if this solved, i will try this on another computer tomorrow

**Comment by W4RH4WK** [comment]
This seems extremely strange to me. A Windows App being installed (or not installed) should not change the network behavior of the OS. And neither `remove-default-apps.ps1` nor `remove-onedrive.ps1` change anything network related.

The scripts disabling telemetry do, they add entries into the `hosts` file and add one firewall rule. Thanks for investigating this issue.

**Comment by xyabcn** [comment]
it not solved with this method, i found if i connect to my network with vpn, then the local website work

**Comment by W4RH4WK** [comment]
I recommend asking one of your companies admins to have a look at it, also show him this issue.

**Comment by W4RH4WK** [comment]
Anything left to do here, or can I close this issue?

**Comment by xyabcn** [comment]
everything is fine now, you can close this issue, thanks for your help
