### ISSUE TITLE
Unable to block Microsoft Telemetry

### ISSUE THREAD

**Issue by rajeevyadav** [W4RH4WK/Debloat-Windows-10#93]
I tried to use the tool but Microsoft telemetry pop-ups again after restart. Also, I want to have fingerprint enabled. Please guide how to reverse that.

Thanks

**Comment by W4RH4WK** [comment]
Can you please attach a screenshot of the telemetry pop-up(s). Just to be sure about what you mean.

I am not entirely sure about the fingerprint thing, but `disable-services` disables the *Windows Biometric Service* which may be required for such interaction. Try re-enabling it.

**Comment by rajeevyadav** [comment]
![capture](https://cloud.githubusercontent.com/assets/3670553/22158878/6758a576-df0c-11e6-8669-79af0b989425.PNG)

You can see the MICROSOFT COMPATIBILITY TELEMETRY process. This process recurs from time to time and eats CPU 100%.

Also, lets say I want to revert back changes done by your scripts, could you please guide me how to? Thanks

**Comment by W4RH4WK** [comment]
The README clearly states that there is no (simple) undo. You'd have to go through all the scripts line by line and try to undo what each command does. This is also why I only recommend running the scripts on a freshly installed system and take a few days to test the setup, so you can just wipe the installation and redo it without much time lost.

Please check if the 2 services *Connected User Experiences and Telemetry (DiagTrack)* and *dmwappushservice* are stopped and disabled. Further issue following command in an elevated cmd.

    echo “” > C:\ProgramData\Microsoft\Diagnosis\ETLLogs\AutoLogger\AutoLogger-Diagtrack-Listener.etl

Also double check if `HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection\AllowTelemetry` is set to 0.

There are also some entries in the task scheduler under `Microsoft > Windows > Application Experience` which you may want to disable.

**Comment by W4RH4WK** [comment]
Any updates?
