### ISSUE TITLE
Start Menu does not Open

### ISSUE THREAD

**Issue by Raffero** [W4RH4WK/Debloat-Windows-10#94]
I run all scripts from script folder and now my taskbar is broken. I can't  open the start menu or taskbar icons like wifi, battery . How can i fix it?

**Comment by W4RH4WK** [comment]
Is that stuff still broken after reboot. or at least when restarting `explorer.exe`?

**Comment by Raffero** [comment]
Still doesnt work. I installed start menu from startisback.com but i cant open icons like battery, wifi, clock.

**Comment by W4RH4WK** [comment]
For the start menu I encourage you to keep using startisback, the Windows 10 Start Menu is the worst. Did you change the scripts in any way, or just used the defaults? I'll try to reproduce it tomorrow in a VM.

**Comment by Raffero** [comment]
I don't change anything, you're right startisback is better. I don't know what caused damage it but my friend said me that he ran all scripts without experimental and everything is fine. I am not using english version of windows 10 if it's important.

**Comment by W4RH4WK** [comment]
I just setup a fresh VM, installed all updates and run the scripts (except experimental unfuckery) without any modifications. The start menu, as well as the tray icons, still work. I'll keep this issue open in case people experience a similar problem.

![image](https://cloud.githubusercontent.com/assets/328798/22619789/7c870b26-eafc-11e6-954d-fe42aaed2cbc.png)

**Comment by Raffero** [comment]
Is it any way to receover changes made by experimental unfuckery?

**Comment by W4RH4WK** [comment]
Nope, at least I don't know of a way. The description of that script basically states that you should not use it unless you know what you are doing anyway.

**Comment by ronen1n** [comment]
did you tried
cmd
sfc/scannow
OR
system restore
