### ISSUE TITLE
install-basic-software.ps1 returns parse error

### ISSUE THREAD

**Issue by Michlass** [W4RH4WK/Debloat-Windows-10#95]
Wen script is called, PS returns the following:

```
At C:\Users\michi\OneDrive\Documents\Debloat-Windows-10-master\utils\install-basic-software.ps1:53 char:27
+ rm "/SysinternalsSuite.zip"
+                           ~
The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString


```

**Comment by W4RH4WK** [comment]
That sounds a bit strange, I'll have a look at it later. Does changing the double quotes to single quote help?

**Comment by JonnyTech** [comment]
Two of the hyphens earlier in the script (preceding Execute and Trigger) are actually dashes, could this cause the problem?

**Comment by W4RH4WK** [comment]
@JonnyTech thanks, I totally missed that. It could have caused the problem indeed. Anyway, the dashes are now replaced.

**Comment by Michlass** [comment]
Wow, never guessed that would be the problem.
Seems to be solved now, thanks guys!

**Comment by W4RH4WK** [comment]
Apparently hyphen, en-dash and em-dash are accepted by PowerShell for commandline arguments, but it seems like the parser breaks somewhere down the line. Sorry for the inconvenience.
