### ISSUE TITLE
Debloat start menu

### ISSUE THREAD

**Issue by majkinetor** [W4RH4WK/Debloat-Windows-10#96]
When you install Windows for the first time start menu is full of garbage. Would it be possible to delete all of it or some specific tools ?

**Comment by W4RH4WK** [comment]
First, just use another start menu, either [Classic Shell](http://www.classicshell.net/) or [Start is Back](http://startisback.com/).

If this does not fit you, [this](https://github.com/W4RH4WK/Debloat-Windows-10/blob/c4699366b52ed4705d38efddd77075bd9da5e77d/scripts/optimize-user-interface.ps1#L115-L118) removes some of the start menu tiles, but only works if your OS language is English, which it should be anyway.

**Comment by majkinetor** [comment]
> First, just use another start menu, either Classic Shell or Start is Back.

Nah, I don't use more bloat to reduce bloat :)

> If this does not fit you, this removes some of the start menu tiles, but only works if your OS language is English, how it should be anyway.

Ah, nice, didn't see that, exactly what I needed. This is the only script I didn't execute, looks too funky.

Thx for the quick answer.
