### ISSUE TITLE
install-basic-software.ps1 - Installed software don't show at packages list or choco gui

### ISSUE THREAD

**Issue by sn4k3** [W4RH4WK/Debloat-Windows-10#98]
I have deployed 3 different machines with a clean install of Windows 10 all with same effect
Using install-basic-software.ps1 it install fine, apps install normaly, but if we run 'cup all -y' or see chocolatey gui installed packages nothing shows and can't upgrande anything.
If i install using cmd manual method: 'cinst something' it work as expected

**Comment by sn4k3** [comment]
Thank you, i will take a look and test.
Please consider add ChocolateyGUI to software list, usefull for users. And also put other most common used software like java but commented by default

**Comment by sn4k3** [comment]
Tested and it fix the problem, now it register well.
Register-ScheduledJob work too but if i go Windows Tasks or CCleaner Tasks i'm unable to find the created task... Not visable. Also i suggest that would be better to run the task under a hidden cmd to prevent quit and change to weekly, two days per week. No need to update all day
Also i advice to remove --force, users will run this once on a fresh install but what if they keep deploying and unsure about if installed or not? It will force install everything losing time and configs in anycase program rebuid user configs. If user want to force he can update script, but by default should be removed imo

**Comment by W4RH4WK** [comment]
Thank you for the feedback.

**Comment by W4RH4WK** [comment]
I merged #90 a few days ago. This should be fixed now too.
